Regenerate Playwright screenshots
LedgerHQ/ledger-live pull request #1061
Opened 2022-08-26 08:28 UTC by thomasrogerlux

### 📝 Description

Screenshots aren't up to date with actual code, this PR regenerate them

### ❓ Context

- **Impacted projects**: `ledger-live-desktop` 
- **Linked resource(s)**: N/A 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

N/A

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2022-08-26 08:28 UTC, thomasrogerlux commented
/generate-screenshots

2022-08-29 08:29 UTC, valpinkman approved these changes

2022-08-29 08:32 UTC, nabil-brn requested changes
This [change](https://github.com/LedgerHQ/ledger-live/pull/1061/files#diff-8be14feb4e98686041dfaf7c0ea8dc5f701daabc18ded3f223ce9c6c3cae558e) is suspect, can you check this flow:

- Open Ledger Live
- Click on Send in the side menu
- Ensure Button "Continue" appears at some point and it stops loading

Then can you ensure the automated test wait for stable state on button before taking the screenshot, [here](https://github.com/LedgerHQ/ledger-live/blob/develop/apps/ledger-live-desktop/tests/specs/general/layout.spec.ts#L22) to fix it.

2022-08-30 12:28 UTC, thomasrogerlux commented
/generate-screenshots

2022-08-30 14:54 UTC, nabil-brn approved these changes

2022-08-31 09:37 UTC, merged