Celo staking LLM - withdraw unlocked funds
LedgerHQ/ledger-live pull request #1208
Opened 2022-09-07 13:34 UTC by marco-figment

### 📝 Description

Adds functionality to withdraw unlocked funds in Celo LLM.

### ❓ Context

- **Impacted projects**: `ledger-live-mobile`
- **Linked resource(s)**: `n/a`

### ✅ Checklist

- [✅ ] **Test coverage** Manual test + video
- [ ✅] **Atomic delivery**
- [ ✅] **No breaking changes**

### 📸 Demo

https://user-images.githubusercontent.com/98154129/188891319-281feb30-9a56-42a3-a733-cc853efe3b9c.mov

2022-09-08 14:26 UTC, hedi-edelbloute commented on apps/ledger-live-mobile/src/families/celo/WithdrawFlow/WithdrawAmount.tsx
> +const Selectable = ({
Can we try to mutualize this component with the one in celo/components directory ?

2022-09-12 07:16 UTC, haammar-ledger requested changes
Can you please also check [my comment](https://github.com/LedgerHQ/ledger-live/pull/1071#discussion_r957522747) on the previous PR?

2022-09-13 11:00 UTC, marco-figment commented on apps/ledger-live-mobile/src/families/celo/WithdrawFlow/WithdrawAmount.tsx
> +  ]);
fixed

2022-09-13 11:04 UTC, marco-figment commented on apps/ledger-live-mobile/src/families/celo/WithdrawFlow/WithdrawAmount.tsx
> +import { useDebounce } from "@ledgerhq/live-common/lib/hooks/useDebounce";
done, except for live-common/lib/currencies, which seems to still require it.

2022-09-13 13:43 UTC, marco-figment commented
Addressed comments.

2022-09-13 17:12 UTC, haammar-ledger commented
@marco-figment There seems to be a lot of lint issues, mostly related to formatting I think.
If you don't do it already, the easiest is to setup your dev IDE to use the `.prettierrc` configs that we provide on each project, you can even set it up to apply the formatting automatically when saving files. :ok_hand:

2022-09-19 15:38 UTC, henrily-ledger commented
LGTM

2022-09-20 09:11 UTC, merged