Support/add yae icon
LedgerHQ/ledger-live pull request #1409
Opened 2022-09-28 18:04 UTC by crypto-smoke

### 📝 Description

Add YAE token icon. Support for tokens was added to ledger live desktop already. 
Token address is 0x4eE438be38F8682ABB089F2BFeA48851C5E71EAF on Ethereum, Binance Smart Chain, and Polygon

### ❓ Context

- **Impacted projects**: `@ledgerhq/live-common` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2022-09-28 19:04 UTC, adrienlacombe-ledger commented
@LFBarreto for you? ty ty

2022-09-29 07:58 UTC, LFBarreto requested changes
svg format tests are failing on the CI you can review them on 
`[Test] Libraries / Test Libraries (ubuntu-latest) (pull_request) `

to run them locally
```
cd libs/ledger-live-common
pnpm jest src/__tests__/svg.ts
```

you cant put linear gradients or defs

2022-09-29 13:48 UTC, adrienlacombe-ledger commented
ty @LFBarreto !

2022-10-06 08:14 UTC, LFBarreto approved these changes

2022-10-06 08:15 UTC, merged