add BCERT svg icon
LedgerHQ/ledger-live pull request #1519
Opened 2022-10-10 13:48 UTC by Blockcerts-Blockchain

Add blockcerts BCERT token icon

### 📝 Description

Add logos for BCERT token - BCERT to ledger. Support for tokens was added to ledger live desktop already

Contract addresses (ethereum)-
BCERT - 0xbb1f919e70ecc55335548d76f5c15a9dc8f5808e

etherscan url: https://etherscan.io/token/0xbb1f919e70ecc55335548d76f5c15a9dc8f5808e

### ❓ Context

- **Impacted projects**: `` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2022-10-29 20:22 UTC, Blockcerts-Blockchain commented
Hi, any other action we can do to move this forward :) ?

2022-11-15 18:16 UTC, Blockcerts-Blockchain commented
Still no reply on that ? How can we move this further ?

2022-11-17 12:57 UTC, LFBarreto commented
hi :wave: in order to integrate BCERT icon to ledger live could you reduce the number of paths of your icon to a minimal number. keeping it as plain as possible. All the paths will be filled with the same color in the end so if you need to work with negative space you need to merge the paths together keeping the difference.

2022-11-17 14:09 UTC, Blockcerts-Blockchain commented
> hi wave in order to integrate BCERT icon to ledger live could you reduce the number of paths of your icon to a minimal number. keeping it as plain as possible. All the paths will be filled with the same color in the end so if you need to work with negative space you need to merge the paths together keeping the difference.

Is there any software that could help doing that ? We're having hard time getting that solved.

2022-11-23 09:41 UTC, LFBarreto requested changes
Some changes are needed and then we can merge :+1:

2022-11-23 09:41 UTC, LFBarreto commented on libs/ledger-live-common/src/data/icons/svg/BCERT.svg
> +<?xml version="1.0" encoding="UTF-8"?>
you can remove this line :+1:

2022-11-23 09:41 UTC, LFBarreto commented on libs/ledger-live-common/src/data/icons/svg/BCERT.svg
> +<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 360 360">
please remove `id` `data-name` `xmlns` attrs
And add `width="360" height="360"` to the attrs

2022-11-23 09:41 UTC, LFBarreto commented on libs/ledger-live-common/src/data/icons/svg/BCERT.svg
> +  <path d="M183,9.87C91.47,9.87,17,84.34,17,175.87s74.47,166,166,166,166-74.47,166-166S274.53,9.87,183,9.87Zm.12,318.39c-84.5,0-153.25-68.74-153.25-153.24S98.62,21.77,183.12,21.77s153.23,68.75,153.23
Please add a `fill` property with the color of your choice to all the `path`

2022-11-23 09:41 UTC, LFBarreto commented on libs/ledger-live-common/src/data/icons/svg/BCERT.svg
> +  <g>
you can remove all the group tags `g` as they are unused and non necessary here.

2022-11-23 14:23 UTC, Blockcerts-Blockchain commented
All done what expected, thanks for the clarification.

2022-11-29 13:39 UTC, mlegall-ledger approved these changes

2022-11-29 13:39 UTC, mlegall-ledger commented
Isn't a changeset required before merging ?

2022-12-20 21:25 UTC, Justkant commented
Bypassing branch protections, the tests are failing because the runners are different for a fork

2022-12-20 21:25 UTC, merged