LIVE-2356 Dependencies update
LedgerHQ/ledger-live pull request #158
Opened 2022-05-24 10:43 UTC by alexalouit

❓ Context

Impacted projects: @ledgerhq/live-common
Linked resource(s): https://ledgerhq.atlassian.net/browse/LIVE-2356

Upgrade stellar-sdk from 10.1.0 to 10.1.1

Live-common maintenance update

✅ Checklist
 Test coverage: Did you write any tests to cover the changes introduced by this pull request?
 Atomic delivery: Is this pull request standalone? In order words, does it depend on nothing else?
 No breaking changes: Does this pull request contain breaking changes of any kind? If so, please explain why.
📸 Demo
N/A

🚀 Expectations to reach
Please make sure you follow these [Important Steps](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps).

Pull Requests must pass the CI and be internally validated in order to be merged.

2022-06-10 16:51 UTC, gre requested changes
what is the test plan for the changed dependencies? please document in the PR description the impact if it can't be covered automatically 🙏 
(also the PR description have some formatting issues)

2022-06-10 16:51 UTC, gre commented on .changeset/stale-llamas-cheer.md
> +upgrade dependencies
this is too vague to understand in a changeset. please precise exactly which dependencies 🙏

2022-06-14 08:29 UTC, haammar-ledger approved these changes

2022-06-24 07:57 UTC, gre approved these changes

2022-06-27 15:43 UTC, merged

2022-06-28 08:23 UTC, gre commented
merged and test coverage isn't checked :'(