Add 'pnpm bootstrap-lib' command
LedgerHQ/ledger-live pull request #1608
Opened 2022-10-18 10:46 UTC by gre

### 📝 Description

This introduces a command `pnpm bootstrap-lib` that creates a library and attach its name in the package.json. This helps creating a new lib each time we need. we can improve over time the template as it's just a folder.

> I made it because i actually needed it, i started using it to create 3 libs and it worked well but i met a rabbit hole to continue on these 3 libs, so i'm just keeping the benefit of having this command in 👍 

```
pnpm bootstrap-lib libs/mynewlibrary
```

will create a new `@ledgerhq/mynewlibrary` package. you can also use it to make an `apps/`

### ❓ Context

- **Impacted projects**: `n/a` 
- **Linked resource(s)**: `n/a` 

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2022-10-19 16:52 UTC, hedi-edelbloute approved these changes

2022-10-20 09:00 UTC, elbywan commented on tools/scripts/bootstrap-lib.sh
> +#!/bin/bash
We're trying to move away from bash scripts and to use [zx](`https://github.com/google/zx`) instead.

2022-10-20 09:03 UTC, elbywan commented on .LIB_TEMPLATE/package.json
> +  "devDependencies": {},
It might be nice to provide jest as a dep since there is jest config file in the template

2022-10-20 09:07 UTC, elbywan requested changes
Thanks for the PR it is great to have this kind of cli commands to bootstrap stuff 👍 💯.

I left a couple of comments about missing deps (and other minor stuff), also I think it would be nice to provide pre-populated `tsconfig` and `eslint` config files harmonized with the rest of our libs.

2022-10-20 10:17 UTC, gre commented on tools/scripts/bootstrap-lib.sh
> +  echo 'Usage: pnpm bootstrap-lib libs/your-new-lib'
the thing is it also is meant to work for `apps/` , in my case it was 1 app and 2 libs that i needed to easily create

2022-10-20 11:57 UTC, elbywan commented on tools/scripts/bootstrap-lib.sh
> +  echo 'Usage: pnpm bootstrap-lib libs/your-new-lib'
Allright 👍

2022-12-18 04:25 UTC, closed without merging