Fix typo on bot CLI use-case
LedgerHQ/ledger-live pull request #168
Opened 2022-05-24 14:40 UTC by haammar-ledger

### ❓ Context

- **Impacted projects**: live-common (bot)
  
- **Linked resource(s)**: n/a

Issue found and fixed by @emmanuelm41 :+1:
The `mutation` parameter was ignored when provided from the CLI.

### ✅ Checklist

- [ ] **Test coverage**: _Did you write any tests to cover the changes introduced by this pull request?_
- [ ] **Atomic delivery**: _Is this pull request standalone? In order words, does it depend on nothing else?_
- [ ] **No breaking changes**: _Does this pull request contain breaking changes of any kind? If so, please explain why._

### 📸 Demo

N/A

### 🚀 Expectations to reach

The mutation parameter can be used from the CLI to execute a single mutation.

2022-05-24 14:49 UTC, gre approved these changes
super curious why it's not causing any issue today 🤔

2022-05-24 14:51 UTC, haammar-ledger commented
> super curious why it's not causing any issue today thinking

@gre it's only when using a `mutation` param on the CLI command. I guess we rarely use that on the standard use of the bot?

2022-05-24 15:38 UTC, valpinkman requested changes
missing changelog

2022-05-31 14:29 UTC, valpinkman approved these changes

2022-05-31 14:30 UTC, valpinkman requested changes
changelog missing

2022-06-29 04:32 UTC, closed without merging