Feat/osmosis
LedgerHQ/ledger-live pull request #179
Opened 2022-05-25 12:22 UTC by henrily-ledger

### ❓ Context

- **Impacted projects**:

live-common + live-desktop

- **Linked resource(s)**:

For more info please check : 
https://github.com/LedgerHQ/ledger-live/pull/155

### ✅ Checklist

- [ ] **Test coverage**: _Did you write any tests to cover the changes introduced by this pull request?_
- [ ] **Atomic delivery**: _Is this pull request standalone? In order words, does it depend on nothing else?_
- [ ] **No breaking changes**: _Does this pull request contain breaking changes of any kind? If so, please explain why._

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2022-05-27 11:19 UTC, gre commented
Checklist on the PR description should be checked, if they can't add an explanation. if this is still a WIP, make the PR a Draft 🙏

2022-06-07 13:39 UTC, lambertkevin approved these changes
Just one thing about the documentation that can be updated later. 
Still a lot of questions regarding the Product team though.

2022-06-14 16:18 UTC, valpinkman requested changes
new naming convention for jobs ;)

2022-06-14 16:18 UTC, valpinkman commented on .github/workflows/bot-coin-osmosis.yml
> +name: Bot 'osmosis on Silicium'
```suggestion
name: [Bot] Osmosis on Silicium
```

2022-07-26 16:06 UTC, gre commented
is it the same as #745  ?

2022-08-09 08:15 UTC, haammar-ledger commented
:information_source: **This should be merged**, last CI failure is an unrelated known issue on LLD UI tests, currently affecting all PRs.

2022-08-09 12:25 UTC, gre commented on libs/ledger-live-common/package.json
> +    "@keplr-wallet/cosmos": "^0.9.16",
was this tackled?

2022-08-10 12:20 UTC, haammar-ledger commented on libs/ledger-live-common/package.json
> +    "@keplr-wallet/cosmos": "^0.9.16",
Now yes :+1::slightly_smiling_face:

2022-08-11 07:33 UTC, haammar-ledger commented
:information_source: **This can be merged, CI failure on [Test] Desktop App (windows) is an unrelated known flakiness issue.**

2022-08-11 16:18 UTC, gre reviewed
it's the first time I'm aware of a coin implementation that depends on another.
did we project this topic in context of future coin modularisation? It may be problematic.
makes me wonder why we didn't consider osmosis to live in the cosmos family?

2022-08-12 07:38 UTC, merged