Feat/add developed by info on my ledger section
LedgerHQ/ledger-live pull request #1976
Opened 2022-11-25 15:59 UTC by GuilaneDen

### 📝 Description

- Remplacement du lien générique du "Learn more" dans "apps installed" Ledger Live Desktop par le lien dédié qui est disponible à travers l'API sous "support url". Dans le cas où support url n'est pas disponible, le "learn more" devrait plutôt utiliser l'URL générique qui est actuellement utilisé.

- Rajout de l'information "Developed by ..." dans "app catalog" et "apps installed"  Ledger Live Desktop et mobile. Pour cela, nous pouvons utiliser "author name" depuis l'API et afficher "Developed by (author name)". Dans le cas où ce champ n'est pas renseigné, nous pourrions plutôt afficher "Developed by 3rd party".

### ❓ Context

- **Impacted projects**: `Ledger-live-desktop``Ledger-live-mobile` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2022-12-14 12:32 UTC, juan-cortes requested changes
Hello! Thank you for the PR, there are a few things that need changing. And also, all the communication needs to be in English here, not everyone understands French so we've agreed on English for the descriptions and comments. The code looks mostly OK to me, we'd still need to see how it looks and get product and design on the loop since I don't know if this is tracked internally 🤔

2022-12-14 12:32 UTC, juan-cortes commented on apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/Item.jsx
> +  const developedBy = authorName || " 3rd party";
This would need to be translated, no hardcoded strings

2022-12-14 12:32 UTC, juan-cortes commented on apps/ledger-live-desktop/static/i18n/el/app.json
> +        "developedBy":"Developed by",
New strings only need to be added to the english language, the rest is handled by the translations team

2022-12-14 12:32 UTC, juan-cortes commented on apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx
> +  const developedBy = authorName || " 3rd party";
Again, no hardcoded strings

2022-12-14 12:32 UTC, juan-cortes commented on apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx
> +          {"by" + developedBy}
Same

2022-12-14 13:10 UTC, chabroA commented
Hey @GuilaneDen, thanks for your PR! 😃 

Since you PR involve some UI changes, could you please add some screenshots illustrating your update in the PR description, for Desktop and Mobile, for easier review and validation.
Also, could you rewrite the description in English to allow everyone in the team to follow along.

Many thanks 🙌

2022-12-22 16:15 UTC, nparigi-ledger commented
Index: apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/AppActions.jsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/AppActions.jsx b/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/AppActions.jsx
--- a/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/AppActions.jsx	(revision 7361ad187a7ff7886043fc341dd457b598dd199c)
+++ b/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/AppActions.jsx	(date 1671725157439)
@@ -6,6 +6,7 @@
 import { useHistory } from "react-router-dom";
 import type { App } from "@ledgerhq/types-live";
 import type { State, Action, InstalledItem } from "@ledgerhq/live-common/apps/types";
+import { useFeature } from "@ledgerhq/live-common/featureFlags/index";
 
 import styled from "styled-components";
 import { Trans } from "react-i18next";
@@ -86,6 +87,8 @@
     isLiveSupported,
     addAccount,
   }: Props) => {
+    const appSpecificSupportLinkFeature = useFeature("appSpecificSupportLink");
+
     const { name, type, supportURL } = app;
     const history = useHistory();
     const { installedAvailable, installQueue, uninstallQueue, updateAllQueue } = state;
@@ -117,8 +120,8 @@
           history.push("/platform");
           break;
         case "app":
-          supportURL
-            ? openURL(supportURL)
+          supportURL && appSpecificSupportLinkFeature?.enabled
+            ? openURL(supportURL || urls.appSupport[name] || urls.appSupport.default)
             : openURL(urls.appSupport[name] || urls.appSupport.default);
           break;
         case "tool":
Index: apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx b/apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx
--- a/apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx	(revision 7361ad187a7ff7886043fc341dd457b598dd199c)
+++ b/apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx	(date 1671722092253)
@@ -1,6 +1,7 @@
 import React, { memo, useMemo, useCallback } from "react";
 
 import { App } from "@ledgerhq/types-live";
+import { useFeature } from "@ledgerhq/live-common/featureFlags/index";
 
 import { State, Action } from "@ledgerhq/live-common/apps/index";
 import { useNotEnoughMemoryToInstall } from "@ledgerhq/live-common/apps/react";
@@ -61,6 +62,7 @@
   setStorageWarning,
   optimisticState,
 }: Props) => {
+  const appAuthorNameFeature = useFeature("appAuthorName");
   const { name, bytes, version: appVersion, displayName, authorName } = app;
   const { installed, deviceInfo } = state;
 
@@ -97,9 +99,11 @@
         >
           {displayName}
         </Text>
-        <Text variant="tiny" fontWeight="medium" color="neutral.c70">
-          {"by" + developedBy}
-        </Text>
+        {appAuthorNameFeature?.enabled && (
+          <Text variant="tiny" fontWeight="medium" color="neutral.c70">
+            {"by" + developedBy}
+          </Text>
+        )}
       </LabelContainer>
       <VersionContainer borderColor="neutral.c40" mx={3}>
         <Text
Index: apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/Item.jsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/Item.jsx b/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/Item.jsx
--- a/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/Item.jsx	(revision 7361ad187a7ff7886043fc341dd457b598dd199c)
+++ b/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/Item.jsx	(date 1671725157451)
@@ -19,6 +19,7 @@
 import AppActions from "./AppActions";
 
 import AppIcon from "./AppIcon";
+import { useFeature } from "@ledgerhq/live-common/featureFlags/index";
 
 const AppRow = styled.div`
   display: flex;
@@ -70,6 +71,7 @@
   setAppUninstallDep,
   addAccount,
 }: Props) => {
+  const appAuthorNameFeature = useFeature("appAuthorName");
   const { name, type, authorName } = app;
   const { deviceModel, deviceInfo } = state;
 
@@ -151,16 +153,18 @@
           </>
         ) : null}
       </Box>
-      <Box flex="0.7" horizontal alignContent="center" justifyContent="flex-start" ml={5}>
-        <>
-          <Ellipsis ml={2} ff="Inter|Regular" color="palette.text.shade60" fontSize={3}>
-            <Trans i18nKey="manager.applist.item.developedBy" />
-            <Text ff="Inter|Bold" color="palette.text.shade100" fontSize={3}>
-              {developedBy}
-            </Text>
-          </Ellipsis>
-        </>
-      </Box>
+      {appAuthorNameFeature?.enabled && (
+        <Box flex="0.7" horizontal alignContent="center" justifyContent="flex-start" ml={5}>
+          <>
+            <Ellipsis ml={2} ff="Inter|Regular" color="palette.text.shade60" fontSize={3}>
+              <Trans i18nKey="manager.applist.item.developedBy" />
+              <Text ff="Inter|Bold" color="palette.text.shade100" fontSize={3}>
+                {developedBy}
+              </Text>
+            </Ellipsis>
+          </>
+        </Box>
+      )}
       <AppActions
         state={state}
         app={app}
Index: libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/libs/ledger-live-common/src/featureFlags/defaultFeatures.ts b/libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
--- a/libs/ledger-live-common/src/featureFlags/defaultFeatures.ts	(revision 7361ad187a7ff7886043fc341dd457b598dd199c)
+++ b/libs/ledger-live-common/src/featureFlags/defaultFeatures.ts	(date 1671638892290)
@@ -169,4 +169,10 @@
   walletNftGallery: {
     enabled: false,
   },
+  appSpecificSupportLink: {
+    enabled: false,
+  },
+  appAuthorName: {
+    enabled: false,
+  },
 };
Index: libs/ledgerjs/packages/types-live/src/feature.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/libs/ledgerjs/packages/types-live/src/feature.ts b/libs/ledgerjs/packages/types-live/src/feature.ts
--- a/libs/ledgerjs/packages/types-live/src/feature.ts	(revision 7361ad187a7ff7886043fc341dd457b598dd199c)
+++ b/libs/ledgerjs/packages/types-live/src/feature.ts	(date 1671635923482)
@@ -36,7 +36,9 @@
   | "receiveStakingFlowConfigDesktop"
   | "ethStakingProviders"
   | "storyly"
-  | "firebaseEnvironmentReadOnly";
+  | "firebaseEnvironmentReadOnly"
+  | "appSpecificSupportLink"
+  | "appAuthorName";
 
 /**  We use objects instead of direct booleans for potential future improvements
 like feature versioning etc */

2022-12-22 16:18 UTC, nparigi-ledger commented
```
Index: apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/AppActions.jsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/AppActions.jsx b/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/AppActions.jsx
--- a/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/AppActions.jsx	(revision 7361ad187a7ff7886043fc341dd457b598dd199c)
+++ b/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/AppActions.jsx	(date 1671725157439)
@@ -6,6 +6,7 @@
 import { useHistory } from "react-router-dom";
 import type { App } from "@ledgerhq/types-live";
 import type { State, Action, InstalledItem } from "@ledgerhq/live-common/apps/types";
+import { useFeature } from "@ledgerhq/live-common/featureFlags/index";
 
 import styled from "styled-components";
 import { Trans } from "react-i18next";
@@ -86,6 +87,8 @@
     isLiveSupported,
     addAccount,
   }: Props) => {
+    const appSpecificSupportLinkFeature = useFeature("appSpecificSupportLink");
+
     const { name, type, supportURL } = app;
     const history = useHistory();
     const { installedAvailable, installQueue, uninstallQueue, updateAllQueue } = state;
@@ -117,8 +120,8 @@
           history.push("/platform");
           break;
         case "app":
-          supportURL
-            ? openURL(supportURL)
+          supportURL && appSpecificSupportLinkFeature?.enabled
+            ? openURL(supportURL || urls.appSupport[name] || urls.appSupport.default)
             : openURL(urls.appSupport[name] || urls.appSupport.default);
           break;
         case "tool":
Index: apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx b/apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx
--- a/apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx	(revision 7361ad187a7ff7886043fc341dd457b598dd199c)
+++ b/apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx	(date 1671722092253)
@@ -1,6 +1,7 @@
 import React, { memo, useMemo, useCallback } from "react";
 
 import { App } from "@ledgerhq/types-live";
+import { useFeature } from "@ledgerhq/live-common/featureFlags/index";
 
 import { State, Action } from "@ledgerhq/live-common/apps/index";
 import { useNotEnoughMemoryToInstall } from "@ledgerhq/live-common/apps/react";
@@ -61,6 +62,7 @@
   setStorageWarning,
   optimisticState,
 }: Props) => {
+  const appAuthorNameFeature = useFeature("appAuthorName");
   const { name, bytes, version: appVersion, displayName, authorName } = app;
   const { installed, deviceInfo } = state;
 
@@ -97,9 +99,11 @@
         >
           {displayName}
         </Text>
-        <Text variant="tiny" fontWeight="medium" color="neutral.c70">
-          {"by" + developedBy}
-        </Text>
+        {appAuthorNameFeature?.enabled && (
+          <Text variant="tiny" fontWeight="medium" color="neutral.c70">
+            {"by" + developedBy}
+          </Text>
+        )}
       </LabelContainer>
       <VersionContainer borderColor="neutral.c40" mx={3}>
         <Text
Index: apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/Item.jsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/Item.jsx b/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/Item.jsx
--- a/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/Item.jsx	(revision 7361ad187a7ff7886043fc341dd457b598dd199c)
+++ b/apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/Item.jsx	(date 1671725157451)
@@ -19,6 +19,7 @@
 import AppActions from "./AppActions";
 
 import AppIcon from "./AppIcon";
+import { useFeature } from "@ledgerhq/live-common/featureFlags/index";
 
 const AppRow = styled.div`
   display: flex;
@@ -70,6 +71,7 @@
   setAppUninstallDep,
   addAccount,
 }: Props) => {
+  const appAuthorNameFeature = useFeature("appAuthorName");
   const { name, type, authorName } = app;
   const { deviceModel, deviceInfo } = state;
 
@@ -151,16 +153,18 @@
           </>
         ) : null}
       </Box>
-      <Box flex="0.7" horizontal alignContent="center" justifyContent="flex-start" ml={5}>
-        <>
-          <Ellipsis ml={2} ff="Inter|Regular" color="palette.text.shade60" fontSize={3}>
-            <Trans i18nKey="manager.applist.item.developedBy" />
-            <Text ff="Inter|Bold" color="palette.text.shade100" fontSize={3}>
-              {developedBy}
-            </Text>
-          </Ellipsis>
-        </>
-      </Box>
+      {appAuthorNameFeature?.enabled && (
+        <Box flex="0.7" horizontal alignContent="center" justifyContent="flex-start" ml={5}>
+          <>
+            <Ellipsis ml={2} ff="Inter|Regular" color="palette.text.shade60" fontSize={3}>
+              <Trans i18nKey="manager.applist.item.developedBy" />
+              <Text ff="Inter|Bold" color="palette.text.shade100" fontSize={3}>
+                {developedBy}
+              </Text>
+            </Ellipsis>
+          </>
+        </Box>
+      )}
       <AppActions
         state={state}
         app={app}
Index: libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/libs/ledger-live-common/src/featureFlags/defaultFeatures.ts b/libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
--- a/libs/ledger-live-common/src/featureFlags/defaultFeatures.ts	(revision 7361ad187a7ff7886043fc341dd457b598dd199c)
+++ b/libs/ledger-live-common/src/featureFlags/defaultFeatures.ts	(date 1671638892290)
@@ -169,4 +169,10 @@
   walletNftGallery: {
     enabled: false,
   },
+  appSpecificSupportLink: {
+    enabled: false,
+  },
+  appAuthorName: {
+    enabled: false,
+  },
 };
Index: libs/ledgerjs/packages/types-live/src/feature.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/libs/ledgerjs/packages/types-live/src/feature.ts b/libs/ledgerjs/packages/types-live/src/feature.ts
--- a/libs/ledgerjs/packages/types-live/src/feature.ts	(revision 7361ad187a7ff7886043fc341dd457b598dd199c)
+++ b/libs/ledgerjs/packages/types-live/src/feature.ts	(date 1671635923482)
@@ -36,7 +36,9 @@
   | "receiveStakingFlowConfigDesktop"
   | "ethStakingProviders"
   | "storyly"
-  | "firebaseEnvironmentReadOnly";
+  | "firebaseEnvironmentReadOnly"
+  | "appSpecificSupportLink"
+  | "appAuthorName";
 
 /**  We use objects instead of direct booleans for potential future improvements
 like feature versioning etc */
```

2022-12-22 16:20 UTC, nparigi-ledger commented
[add_two_feature_flags.txt](https://github.com/LedgerHQ/ledger-live/files/10288458/add_two_feature_flags.txt)

Hello @GuilaneDen, please apply this .patch file to your PR.
It will add two feature flags, appSpecificSupportLink and appAuthorName, to remote control the new app support link and app developer name features

2023-01-16 04:26 UTC, closed without merging