Support/add waifu token logo
LedgerHQ/ledger-live pull request #2451
Opened 2023-01-27 18:36 UTC by demonslayer69420

### 📝 Description
![image](https://user-images.githubusercontent.com/104881565/215167505-4633fa5d-ce0a-49d2-a2ba-82f43df59803.png)

Add logo for Waifu token
https://bscscan.com/token/0xd0aa796e2160ED260c668E90aC5f237b4eBd4b0d https://waifutoken.net/

### ❓ Context

- **Impacted projects**: `` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-01-28 02:51 UTC, demonslayer69420 commented
@Justkant kindly review the pr

2023-01-31 09:51 UTC, Justkant requested changes
Small issue with the changeset, also I think you'll need to cleanup a bit the svg, we'll see what the CI tells us

2023-01-31 09:51 UTC, Justkant commented on .changeset/waifu-token.md
> +"@ledgerhq/live-common": patch
Please remove the `ledger-live-desktop` changeset as you only modified ledger-live-common
```suggestion
"@ledgerhq/live-common": patch
```

2023-01-31 10:00 UTC, demonslayer69420 commented
@Justkant i have updated the change set, kindly review

2023-01-31 12:28 UTC, adrienlacombe-ledger commented
@demonslayer69420 the filename must the same as the token ticker

2023-01-31 13:55 UTC, demonslayer69420 commented
> @demonslayer69420 the filename must the same as the token ticker

@adrienlacombe-ledger apologies, i have updated the file, sorry to keep troubling you over something this small

2023-01-31 15:02 UTC, closed without merging