feat: Cryptoorg coin modularization
LedgerHQ/ledger-live pull request #2664
Opened 2023-02-16 09:06 UTC by hedi-edelbloute

remove coin specific logic outside its family folder

### 📝 Description

Remove cryptoorg coin specific logic outside of its family folder

### ❓ Context

- **Impacted projects**: `LLC` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4939 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-03-16 10:42 UTC, gre commented
@hedi-edelbloute FYI there are still some conflict about reconciliation.ts on this PR.

2023-03-17 09:40 UTC, lvndry approved these changes

2023-03-17 09:54 UTC, henrily-ledger approved these changes

2023-03-17 13:37 UTC, henrily-ledger requested changes
Does assignToAccountRaw and assignFromAccountRaw is on bridge/js.ts

2023-03-20 13:58 UTC, hedi-edelbloute commented
> Does assignToAccountRaw and assignFromAccountRaw is on bridge/js.ts

Indeed that was a mistake, thanks, changes made

2023-03-22 15:31 UTC, merged