BACK-4796: Prefix testnet token ticker with "t" in transaction config…
LedgerHQ/ledger-live pull request #2828
Opened 2023-03-02 19:01 UTC by henrily-ledger

### 📝 Description

See https://ledgerhq.atlassian.net/wiki/spaces/~623066f962dc1e006801f92c/pages/4071784452/BACK-4796+Ledger+Live+signature+mismatch+for+Go+rli+tokens

https://github.com/LedgerHQ/ledger-live/pull/2690

### ❓ Context

- **Impacted projects**: `` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-03-10 17:23 UTC, jnicoulaud-ledger commented
@henrily-ledger: Updated signatures in #2907

2023-03-16 13:09 UTC, henrily-ledger commented on libs/ledgerjs/script/crypto-assets-importer/importers/erc20-signatures.js
> +      const prefix = currency.isTestnetFor !== undefined ? 't': '';
No is not I guess 

![Uploading Screenshot 2023-03-16 at 14.09.07.png…]()

2023-03-20 08:16 UTC, adrienlacombe-ledger commented
IT seems that https://github.com/LedgerHQ/ledger-live/pull/2828/files#diff-ddf7ce79297278369f2dced95df9c3ee3ef5257283480762df58bf1a122bdcafR52 updates tickers, which was never done before. Also, this test https://github.com/LedgerHQ/ledger-live/actions/runs/4446143749/jobs/7806099220#step:9:4776 precisely check for ticker consistently therefore failing as expected. I see 2 options here: update of the test suite to remove this check for testnet tokens OR update the tickers on both sides i.e. in the CAL as well.

2023-03-24 11:11 UTC, gre requested changes
there is a new file ethereum.json that is  381,179 line of code, i'm not sure we want it in?

2023-03-24 11:43 UTC, jnicoulaud-ledger commented
@gre yes, that is a mistake, I will update this PR later today

2023-03-24 17:38 UTC, jnicoulaud-ledger commented
This should be better:

- rebased
- removed extra `ethereum.json`
- fixed test

Note: I had to run importers using the latest CAL (https://github.com/LedgerHQ/crypto-assets/commit/e97b76d6d9fa217ad70dc08a03f4a97ea00008ea), so this includes a CAL update as well, this is why there more are changes than just testnet signatures.

2023-03-27 08:23 UTC, jnicoulaud-ledger commented
Test now failing because firmware upgrade prompt is not shown on linux:
![image](https://user-images.githubusercontent.com/102984500/227883945-862b0b88-980b-489a-8033-18d50695649c.png)
I don't think it's related to this PR

2023-03-27 15:18 UTC, haammar-ledger approved these changes

2023-03-27 15:23 UTC, merged