Feat/hedera remove network calls from estimate fees
LedgerHQ/ledger-live pull request #3032
Opened 2023-03-22 18:13 UTC by Sheng-Long

### 📝 Description

This change removes network calls from functions having to do with estimating fees for Hedera Transactions

### ❓ Context

- **Impacted projects**: `` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-03-24 09:38 UTC, gre requested changes

2023-03-24 09:38 UTC, gre commented on libs/ledger-live-common/src/families/hedera/bridge.integration.test.ts
> +                status.estimatedFees.toNumber() * estimatedFeeSafetyRate
we shouldn't have to convert back to number. instead it should be `status.estimatedFees.times(estimatedFeeSafetyRate)` (or multipliedBy)

2023-03-24 09:38 UTC, gre commented on libs/ledger-live-common/src/families/hedera/tests/utils.test.ts
> +  const estimatedFees = new BigNumber("150200"); // 0.001502 ℏ (as of 2023-03-14)
shouldn't this be imported from hedera/utils ?

2023-03-29 13:38 UTC, haammar-ledger requested changes
As discussed on Discord -- before approving I'd like to know the justification for this revert of the dynamic fees.

2023-03-30 18:06 UTC, closed without merging