Feat/PROTECT-1720 - LLD Nano onboarding to include a screen about recover
LedgerHQ/ledger-live pull request #3507
Opened 2023-05-24 17:56 UTC by nparigi-ledger

### 📝 Description

Add an upsell recover message after classic onboarding

### ❓ Context

- **Impacted projects**: `` live-common, live-desktop
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/PROTECT-1720
- 
### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-05-25 06:42 UTC, jules-grenier-ledger approved these changes
LGTM

2023-06-02 09:55 UTC, gre requested changes
👋  we have recently merged https://github.com/LedgerHQ/ledger-live/pull/3455 in develop branch which reinforces the TypeScript checks, mostly related to modals and coin families. Could you rebase and check that everything still pass?

Thanks,
gre.

2023-06-02 09:55 UTC, gre commented on libs/ledger-live-common/src/hooks/recoverFeatueFlag.ts
> +  servicesConfig: Feature<any> | null
`any` is no longer allowed on LLD project, you can possibly use the correct type OR unknown (which will requires you to do a lot of typecheck in the JS if you use unknown)

2023-06-12 07:34 UTC, Justkant commented
done in #3644

2023-06-12 07:34 UTC, closed without merging