[support] Remove live-portfolio lib
LedgerHQ/ledger-live pull request #3521
Opened 2023-05-26 12:23 UTC by haammar-ledger

### 📝 Description

This is a proposal to remove the recently created `live-portfolio` lib, which contains very little code and is a bit overkill at the moment. It's scope isn't very clear either, I think it was intended for any other util that could be shared by both the portfolio section + other parts of the code, but there is no foreseeable need at the moment.

The compromise is to split the code that the lib currently contains into the different places where it's used, which causes only a little duplication. The necessary duplicate code is exactly this, which seemed acceptable to me:
```
const hourIncrement = 60 * 60 * 1000;
const dayIncrement = 24 * hourIncrement;
const weekIncrement = 7 * dayIncrement;

export function startOfHour(t: Date): Date {
  return new Date(t.getFullYear(), t.getMonth(), t.getDate(), t.getHours());
}
export function startOfDay(t: Date): Date {
  return new Date(t.getFullYear(), t.getMonth(), t.getDate());
}
export function startOfWeek(t: Date): Date {
  const d = startOfDay(t);
  return new Date(d.getTime() - d.getDay() * dayIncrement);
}
```
### ❓ Context

- **Impacted projects**: `coin-framework` `ledger-live-common` `live-portfolio` 
- **Linked resource(s)**: N/A 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

Nothing to demo.

### 🚀 Expectations to reach

Live still builds. 100% covered by CI.

2023-06-01 13:50 UTC, sprohaszka-ledger requested changes
I still think that we may need some "utils" pkg (even if I hate this name).
In the meantime I agree to remove this skinny package, but we need the unit tests in those 2 packages.

2023-06-09 07:59 UTC, sprohaszka-ledger commented on libs/coin-framework/src/account/helpers.test.ts
I wouldn't put those tests into this file. I think it's easier to trace the code and their tests by having them in a file with the same name. I would have put those tests into a `balanceHistoryCache.test.ts` file.

2023-06-12 09:36 UTC, gre commented
👋  ESLint config has been unified on develop after we merged https://github.com/LedgerHQ/ledger-live/pull/3622 – this will improve the project consistency, remove eslint dependencies duplicates, and overall simplify the maintenance. This comes with a prettier library upgrade and unification of the prettierrc too, so you likely have conflicts with develop.


Hopefully, here is the procedure to easily fix this. **please proceed as follow**:

**Step 1: sync your branch with develop up to the config changes:**

2 cases

- if your branch were continuously rebased with develop and don't have any merge commit, you can do 
```
git rebase aa1e0ebc0a0498b4350754899b6a368fbd42e811
```
- otherwise prefer 
```
git merge aa1e0ebc0a0498b4350754899b6a368fbd42e811
```

**then, apply the config**

```
pnpm i
pnpm lint:fix --force
```

if there are remaining errors that lint couldn't fix, please fix them and `pnpm lint` again.

then commit in your branch.

```
git commit -a -m "chore: lint fixes"
```

**Step 2: finalize the rebase/merge with develop**

2 cases

- if your branch were continuously rebased with develop and don't have any merge commit, you can do
```
git pull --rebase origin develop
```
- otherwise prefer 
```
git merge origin/develop
```

you should now be up to date. 👍

---

*Thanks and sorry for the inconvenience,*
*gre*

2023-06-13 09:15 UTC, gre approved these changes

2023-06-16 19:53 UTC, merged