fix: support wallet api accountId manifests
LedgerHQ/ledger-live pull request #3583
Opened 2023-06-05 14:03 UTC by sarneijim

### 📝 Description

When manifest are using wallet-api account context is incorrect.

### ❓ Context

- **Impacted projects**: LLD
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7658

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-06-05 15:37 UTC, beths-ledger approved these changes

2023-06-05 16:07 UTC, adrienlacombe-ledger commented
do not merge, I would like to better understand what you are trying to achieve first

2023-06-05 16:09 UTC, sarneijim commented
Pending to discuss with @adrienlacombe-ledger

2023-06-06 08:14 UTC, IAmMorrow requested changes
This component is currently responsible for blindly forwarding the parameters to the WebPlatformPlayer (and so to the live apps). This PR changes its behavior by making it react to some very specific param key for the Paraswap / 1Inch scenario. I think this is not optimal as it would effectively make the component smarter thank it should be and increase complexity / maintenance cost.

I think I would implement this logic where the redirect is initially done (probably in the swap logic ?). If we can't dynamically adapt to the manifest version, a feature flag is probably okay to pilot this since this is a one shot migration and not something that will keep being used in the future 🤞

2023-06-06 08:14 UTC, IAmMorrow commented on apps/ledger-live-desktop/src/renderer/screens/platform/App.tsx
> +  if (manifest.apiVersion === "^2.0.0 || ^1.0.0") {
FYI we have a semver package that should be used for any semver logic :)

2023-06-06 08:25 UTC, closed without merging