[fix/LIVE-7772]: only navigation pop if navigation index is > 0.
LedgerHQ/ledger-live pull request #3595
Opened 2023-06-06 15:16 UTC by kallen-ledger

### 📝 Description
Fixes bug where user was returned to initial page of buy app after selecting account.

- Tested buy on ActionBar, Asset, Account, Market  ✅ 
- Testing eth liquid staking modal ActionBar, Asset, Account, Market ✅ 
- Testing native staking ActionBar, Asset, Account, Market ✅ 

### ❓ Context

- **Impacted projects**: `LLM` 
- **Linked resource(s)**: `LIVE-7772` 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo
Original bug.

https://github.com/LedgerHQ/ledger-live/assets/132384348/7836ac4f-a6e5-4b9d-9d84-df0660686008

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-06-06 15:41 UTC, mitchellv-ledger approved these changes
LGTM

2023-06-06 15:46 UTC, sarneijim approved these changes

2023-06-07 08:43 UTC, cksanders requested changes
OK seems the regression was caused by https://github.com/LedgerHQ/ledger-live/pull/3526/files#r1221273156, which resulted in the error message `'JSON-RPC method account.request responded an error', [Error: Request account interrupted by user]` ...

2023-06-07 10:12 UTC, cksanders commented
Closing in favour of https://github.com/LedgerHQ/ledger-live/pull/3607 ... ideally, we want to revert rather than update functionality - especially as it affects all account selection pages and seems there are no tests to ensure no further unforeseen regression.

2023-06-07 10:12 UTC, closed without merging