fix: typescript polkadot icon
LedgerHQ/ledger-live pull request #3867
Opened 2023-06-29 15:55 UTC by henrily-ledger

### 📝 Description

Fix typescripting for LLM and LLD of polkadot icon

### ❓ Context

- **Impacted projects**: `LLD LLM` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-06-29 15:58 UTC, hedi-edelbloute requested changes
Please explain why we don't cross the text coverage checkbox (atleast it's not a copy pasta @haammar-ledger )

2023-06-29 17:25 UTC, lvndry approved these changes

2023-06-29 17:25 UTC, lvndry commented on apps/ledger-live-desktop/src/renderer/families/polkadot/Nomination/Row.tsx
>  const Wrapper = styled.div`
```suggestion
import Identicon from "@polkadot/react-identicon";

const Wrapper = styled.div`
```

2023-06-29 17:25 UTC, lvndry commented on apps/ledger-live-desktop/src/renderer/families/polkadot/NominationFlowModal/fields/ValidatorRow.tsx
>  const IconContainer = styled.div`
```suggestion
import Identicon from "@polkadot/react-identicon";

const IconContainer = styled.div`
```

2023-06-30 12:35 UTC, henrily-ledger commented
/generate-screenshots

2023-06-30 12:42 UTC, gre approved these changes

2023-06-30 12:43 UTC, mcoursier-ledger approved these changes

2023-07-03 10:30 UTC, haammar-ledger approved these changes

2023-07-03 10:31 UTC, merged