feat(hedera): add memo capability
LedgerHQ/ledger-live pull request #394
Opened 2022-06-17 18:54 UTC by jackthta

### 📝 Description

This PR will add the memo capability to Hedera.

### ❓ Context

- **Impacted projects**: `Ledger Live Common & Ledger Live Desktop` 
- **Linked resource(s)**: `N/A` 

### ✅ Checklist

- [X] **Test coverage** 
- [X] **Atomic delivery** 
- [X] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2022-06-20 15:57 UTC, aelmilligy-ledger commented
Hi @jackthta,
Could you have a look on the lint, some checks were not successful because of it. Also, could you include changesets to this PR?

2022-06-21 18:13 UTC, haammar-ledger commented
@aelmilligy-ledger Note: this PR could be reviewed first then targeted to `feat/hedera` instead of `develop`, to also run the bot on these changes.

2022-06-21 18:13 UTC, haammar-ledger commented
@jackthta Can you please add mutations to the bot's spec file, to test transactions that include a memo?

2022-06-21 19:18 UTC, jackthta commented on apps/ledger-live-desktop/scripts/sync-families-dispatch.sh
> +StepAmount.js \
Will do 👍

2022-06-22 13:21 UTC, aelmilligy-ledger commented
Hi @jackthta,
Regarding the checks made after your commits, there are still some linter issues. Also, please consider to rebase or merge in order to ensure that your branch is up-to-date.

2022-06-22 17:02 UTC, jackthta commented
> Hi @jackthta, Regarding the checks made after your commits, there are still some linter issues. Also, please consider to rebase or merge in order to ensure that your branch is up-to-date.

Hi @aelmilligy-ledger,
Sorry about that, I believe it should be good now, but please do let me know if otherwise.

2022-06-29 08:21 UTC, haammar-ledger requested changes

2022-06-29 08:21 UTC, haammar-ledger commented on apps/ledger-live-desktop/src/renderer/families/hedera/types.js
> +  mapStrategies?: FeeStrategy => FeeStrategy & { [string]: * },
Very minor, but these 2 props seem unused, and this is causing a failure in that CI test: https://github.com/LedgerHQ/ledger-live/runs/7099372918?check_suite_focus=true

2022-07-01 10:06 UTC, henrily-ledger commented
Thanks @jackthta we did take the PR and add the missing small fix, we will close it since we cherry-pick commits and merge it to feat/hedera

2022-07-01 10:06 UTC, closed without merging