[LIVE-2497] - Bugfix: Handle reorg on Eth family sync
LedgerHQ/ledger-live pull request #408
Opened 2022-06-20 20:51 UTC by lambertkevin

Draft to fix the reorg issue on the Eth family

### ❓ Context

- **Impacted projects**: `live-common` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-2497` 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2022-06-21 09:00 UTC, gre requested changes

2022-06-21 10:27 UTC, lambertkevin commented on libs/ledger-live-common/src/families/ethereum/synchronisation.ts
> +    .then(Boolean);
Done 👌

2022-06-21 10:29 UTC, lambertkevin commented on libs/ledger-live-common/src/bridge/jsHelpers.ts
> +              family === "ethereum"
Ok I introduced a new parameter to `makeSync` with `shouldMergeOps` with a default behaviour at `true` to ensure compatibility with the other coins.

I'm not really fond of adding new layers of compatibility without it being very visible and logical to mostCases, but I guess it's still a way better option than my "it ethereum" 👍

2022-06-23 17:59 UTC, haammar-ledger approved these changes
LGTM

2022-06-23 18:00 UTC, haammar-ledger commented on libs/ledger-live-common/src/bridge/jsHelpers.ts
> +              family === "ethereum"
@gre please confirm if the proposed solution is acceptable to you.

2022-06-24 08:04 UTC, gre requested changes

2022-06-24 08:12 UTC, gre commented on libs/ledger-live-common/src/families/ethereum/test-dataset.ts
> +};
can you move this directly in synchronisation.integration.test.ts ? this test-dataset.ts file is soon gone.

2022-06-27 10:43 UTC, gre commented
https://github.com/LedgerHQ/ledger-live/actions/runs/2568591731

2022-06-29 18:12 UTC, lambertkevin commented
Just for further investigation, here is a problematic transactions generating subOperations with the same ids that are now mutated by `mergeOps` when not adding the index in the subOperation id:

```json
{
  "hash": "0xe715b4530e40a59f9c943089ff80fc57415687daded99d289574c3dd6e125c4b",
  "transaction_type": 0,
  "nonce": "0x10",
  "value": 0,
  "gas": 334044,
  "gas_price": 5110000001,
  "max_fee_per_gas": null,
  "max_priority_fee_per_gas": null,
  "from": "0x58e327d64fc77fa36f698989623c3e4f058c8a89",
  "to": "0x4f833a24e1f95d70f028921e27040ca56e09ab0b",
  "transfer_events": {
      "list": [
          {
              "contract": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
              "from": "0x0e3f0bb9516f01f2c34c25e0957518b8ac9414c5",
              "to": "0x6924a03bb710eaf199ab6ac9f2bb148215ae9b5d",
              "count": 37531836988865469
          },
          {
              "contract": "0xd26114cd6ee289accf82350c8d8487fedb8a0c07",
              "from": "0x6924a03bb710eaf199ab6ac9f2bb148215ae9b5d",
              "to": "0x0e3f0bb9516f01f2c34c25e0957518b8ac9414c5",
              "count": 5000000000000000000
          },
          {
              "contract": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
              "from": "0x0e3f0bb9516f01f2c34c25e0957518b8ac9414c5",
              "to": "0x58e327d64fc77fa36f698989623c3e4f058c8a89",
              "count": 1752163011134531
          }
      ],
      "truncated": false,
      "next_index": null
  },
  "erc721_transfer_events": [],
  "erc1155_transfer_events": [],
  "approval_events": [],
  "actions": [
      {
          "from": "0x58e327d64fc77fa36f698989623c3e4f058c8a89",
          "to": "0x4f833a24e1f95d70f028921e27040ca56e09ab0b",
          "input": null,
          "value": 0,
          "gas": 282628,
          "gas_used": 171280,
          "error": null
      },
      {
          "from": "0x4f833a24e1f95d70f028921e27040ca56e09ab0b",
          "to": "0x2240dab907db71e64d3e0dba4800c83b5c502d4e",
          "input": null,
          "value": 0,
          "gas": 169859,
          "gas_used": 15079,
          "error": null
      },
      {
          "from": "0x2240dab907db71e64d3e0dba4800c83b5c502d4e",
          "to": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
          "input": null,
          "value": 0,
          "gas": 165834,
          "gas_used": 13625,
          "error": null
      },
      {
          "from": "0x4f833a24e1f95d70f028921e27040ca56e09ab0b",
          "to": "0x2240dab907db71e64d3e0dba4800c83b5c502d4e",
          "input": null,
          "value": 0,
          "gas": 153405,
          "gas_used": 20870,
          "error": null
      },
      {
          "from": "0x2240dab907db71e64d3e0dba4800c83b5c502d4e",
          "to": "0xd26114cd6ee289accf82350c8d8487fedb8a0c07",
          "input": null,
          "value": 0,
          "gas": 149637,
          "gas_used": 19416,
          "error": null
      },
      {
          "from": "0x4f833a24e1f95d70f028921e27040ca56e09ab0b",
          "to": "0x2240dab907db71e64d3e0dba4800c83b5c502d4e",
          "input": null,
          "value": 0,
          "gas": 131263,
          "gas_used": 15079,
          "error": null
      },
      {
          "from": "0x2240dab907db71e64d3e0dba4800c83b5c502d4e",
          "to": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
          "input": null,
          "value": 0,
          "gas": 127841,
          "gas_used": 13625,
          "error": null
      }
  ],
  "confirmations": 7017716,
  "input": null,
  "gas_used": 207696,
  "cumulative_gas_used": 7559212,
  "status": 1,
  "received_at": "2019-06-25T15:51:05Z",
  "block": {
      "hash": "0x441327cd5cb1def0af67178078788ae08715f0a46260ea5e92acf7b73c728fcf",
      "height": 8028070,
      "time": "2019-06-25T15:51:05Z"
  }
}
```

2022-06-30 08:49 UTC, gre approved these changes

2022-06-30 10:07 UTC, lambertkevin commented
Except for a timeout issue on the integration test, we're good. `feature ready` 🙆‍♂️

2022-07-06 13:09 UTC, merged