Bugfix Live-8247 Cosmos undelegate/redelegate LLM error when available balance is not enough
LedgerHQ/ledger-live pull request #4108
Opened 2023-07-21 16:05 UTC by hzheng-ledger

### 📝 Description

In LLM cosmos account, when user available balance is too low to pay transaction fee, we don't have any check on UI side. So user can continue the transaction and finally get an error from Rpc node. We should give user balance error message on UI side before the transaction broadcast and the "continue button" should be disabled.
The LLD has such balance check, so the LLM should have the same behaviour.

### ❓ Context

- **Impacted projects**: `` LLM
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-8247

### ✅ Checklist

- [] **Test coverage** The fix is on LLM UI part, I add some balance check on UI part and raise error if available balance is low. It is very hard to write unit test for this bug.
- [X] **Atomic delivery** 
- [X] **No breaking changes** 

### 📸 Demo
On LLM, when available balance is too low:
![image_123986672](https://github.com/LedgerHQ/ledger-live/assets/71653044/dd7dfcc4-1984-45eb-91ab-3ae222e74b0f)
on LLD,

<img width="496" alt="Screenshot 2023-07-21 at 18 03 35" src="https://github.com/LedgerHQ/ledger-live/assets/71653044/1231a56d-0aa3-4c4f-a217-536dfebe80ab">

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-07-24 12:24 UTC, haammar-ledger requested changes

2023-07-24 12:24 UTC, haammar-ledger commented on apps/ledger-live-mobile/src/families/cosmos/shared/02-SelectAmount.tsx
> +                hasError={isAmountOutOfRange || isNotEnoughBalance}
The UI should contain as little blockchain logic as possible, these components must keep relying on `error`, and the changes must be done in the `getTransactionStatus` function instead.

2023-07-24 12:25 UTC, hedi-edelbloute requested changes
This should come from getTransactionStatus imo

2023-07-25 07:35 UTC, haammar-ledger approved these changes
After discussion, this PR doesn't introduce new tech debt, as the whole component should be reworked, and this is out of scope for this bugfix.
A ticket should be created to rework the `getTransactionStatus` function and the whole component to use it.

2023-07-27 09:29 UTC, merged