Feat/live 7618
LedgerHQ/ledger-live pull request #4251
Opened 2023-08-08 08:47 UTC by sshmaxime

### 📝 Description

Reworking the language components accross LLD.

### ❓ Context

- **Impacted projects**: `LLD` 
- **Linked resource(s)**: [LIVE-7618] 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

Small breaking change because the language system has been changed.

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-08-09 09:26 UTC, sshmaxime commented
/generate-screenshots

2023-08-18 10:25 UTC, ofreyssinet-ledger commented
Didn't check the code yet but several remarks on the PR:
- Maybe try to make PR title a bit more explicit so it's easy to find etc.
- Also can you elaborate a bit the description please ? What has been reworked, why etc. Make it exhaustive if possible.
- [You will also need a changeset](https://github.com/LedgerHQ/ledger-live/pull/4251#issuecomment-1669189087) (`pnpm changeset`) so that your changes appear in the changelogs of the next release. Makes it easy to track what is included in a given release in case there is an issue.
- can you elaborate on that please ? 
  > Small breaking change because the language system has been changed.

2023-08-21 10:38 UTC, sshmaxime commented
/generate-screenshots

2023-08-21 12:14 UTC, sshmaxime commented
/generate-screenshots

2023-08-21 17:07 UTC, KVNLS requested changes
Great work, you improved our translation management a lot! 🎉
Just a small type detail and you're good to merge.

2023-08-21 17:07 UTC, KVNLS commented on apps/ledger-live-desktop/src/renderer/reducers/settings.ts
> +    const languageLocales = Languages[languageId].locales as Locales;
If I define 
`export const Languages: LanguageMap<LanguageDefinition> = {} as const` I can avoid this hack
Could you check if it satisfies what you expect, please?

When I do the change I have relevant errors as follows:
```

 Running typescript type checker on 1657 files…
apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/restore/Language.tsx:29:5 - error TS18048: 'DEFAULT_LANGUAGE.deviceSupport' is possibly 'undefined'.

29     DEFAULT_LANGUAGE.deviceSupport.label,
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/ChangeDeviceLanguagePromptDrawer.tsx:80:15 - error TS18048: 'DEFAULT_LANGUAGE.deviceSupport' is possibly 'undefined'.

80               DEFAULT_LANGUAGE.deviceSupport.label
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

That makes sense as we define 
` deviceSupport: { label: DeviceLanguages; id: number } | undefined;`

2023-08-22 07:51 UTC, ofreyssinet-ledger requested changes
Very neat, great job! Thanks for taking care of that.
Please generate a changeset so these changes appear in the changelog of the next release 👍

2023-08-22 08:44 UTC, ofreyssinet-ledger approved these changes

2023-08-22 09:03 UTC, merged