Fix: LIVE-8269 cosmos amount string parser
LedgerHQ/ledger-live pull request #4281
Opened 2023-08-10 08:31 UTC by hzheng-ledger

### 📝 Description
In the response of cosmos events from explorer. The "amount" field string can contain prefix. Our parser should be able to remove this prefix and get the correct amount string. Otherwise, it will cause a bug in the portfolio graph because of the incorrect amount.

It is a problem due to the multi chain rewards update of cosmos. Before the update, we didn't have this prefix as the follows:

```
{
                  "key": "amount",
                  "value": "11717uosmo"
},

```
Now we can have prefix of the amount value since multi chain rewards update
```
{
                  "key": "amount",
                  "value": "56ibc/0025F8A87464A471E66B234C4F93AEC5B4DA3D42D7986451A059273426290DD5,512ibc/6B8A3F5C2AD51CD6171FA41A7E8C35AD594AB69226438DB94450436EA57B3A89,11717uosmo"
},

```
we should remove the prefix to get the correct value

### ❓ Context

- **Impacted projects**: LLC
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8269

### ✅ Checklist

- [X] **Test coverage** 
- [X] **Atomic delivery** 
- [X] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-08-10 08:44 UTC, lvndry commented on libs/ledger-live-common/src/families/cosmos/logic.ts
> +export function parseAmountStringToNumber(amountString: string, unitCode): string {
```suggestion
export function parseAmountStringToNumber(amountString: string, unitCode: string): string {
```

2023-08-10 08:55 UTC, hzheng-ledger commented on libs/ledger-live-common/src/families/cosmos/logic.ts
> +export function parseAmountStringToNumber(amountString: string, unitCode): string {
fixed

2023-08-10 14:07 UTC, haammar-ledger requested changes
Just needs a changeset. Thanks :)

2023-08-11 08:29 UTC, hzheng-ledger commented
changeset added

2023-08-11 10:04 UTC, haammar-ledger approved these changes

2023-08-11 10:05 UTC, hzheng-ledger commented
/prbot describe

2023-08-16 08:52 UTC, merged