fix: correct estimated fees so that max spendable works as intended
LedgerHQ/ledger-live pull request #4823
Opened 2023-09-22 16:13 UTC by Sheng-Long

### 📝 Description

Fix estimated fee so that max spendable works as intended

### ❓ Context

- **Impacted projects**: `` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-09-25 13:55 UTC, haammar-ledger requested changes
Please add a changeset using `pnpm changeset`

2023-09-25 13:55 UTC, haammar-ledger commented on libs/ledger-live-common/src/families/hedera/utils.ts
> +    return new BigNumber(10000).dividedBy(data[0]).dp(0);
Can you please consider using `integerValue` instead.
I am thinking calling `BigNumber.config` could have side effects.

2023-09-27 16:02 UTC, haammar-ledger approved these changes

2023-09-27 20:41 UTC, Sheng-Long commented
It doesn't seem like the failures here were due to any changes in the PR

2023-10-13 11:00 UTC, haammar-ledger commented
@Sheng-Long Apologies we've been having many stability issues with our CI lately, hopefully it should be more stable now.
Can you please rebase on `develop`? Let's give this another go.

2023-10-18 09:17 UTC, merged