LLM - Fixed a Recover button and changed the order of the Transfer Drawer buttons
LedgerHQ/ledger-live pull request #4924
Opened 2023-10-04 06:13 UTC by cgrellard-ledger

### 📝 Description

small modif on the name of a param from the protectServicesMobile feature flag. Also the recover button is now displayed before the wallet connect button in the quick actions

### ❓ Context

- **Impacted projects**: `ledger-live-mobile` 
- **Linked resource(s)**: [LIVE-9485] 

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-10-04 07:02 UTC, mcayuelas-ledger approved these changes
LGTM

2023-10-04 08:18 UTC, stephane-lieumont-ledger approved these changes

2023-10-06 14:06 UTC, stephane-lieumont-ledger commented on apps/ledger-live-mobile/src/components/ServicesWidget/Protect/useProtect.ts
> +    onLogin();
Great point 👍

2023-10-06 15:51 UTC, stephane-lieumont-ledger requested changes

2023-10-06 15:51 UTC, stephane-lieumont-ledger commented on apps/ledger-live-mobile/src/components/ServicesWidget/Protect/useProtect.ts
> +    onLogin();
Need to keep onLearnMore() link

2023-10-09 09:07 UTC, merged