Bugfix/LIVE-2373 Fix zec parser for v5 transaction
LedgerHQ/ledger-live pull request #497
Opened 2022-06-28 10:15 UTC by hzheng-ledger

### 📝 Description

Fix zec parser for v5 transaction

### ❓ Context

- **Impacted projects**: `` None
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-2373

### ✅ Checklist

- [ ] **Test coverage** 
- [X] **Atomic delivery** 
- [X] **No breaking changes** 

### 📸 Demo

No demo as it is a bug fix

### 🚀 Expectations to reach
User is able to spent v5 utxo transaction with Ledger Live

2022-07-01 08:58 UTC, haammar-ledger requested changes
@hzheng-ledger can you please add a changeset?
Also, do you think it's possible to cover this change with a test?
Thanks.

2022-07-01 08:58 UTC, haammar-ledger commented on libs/ledgerjs/packages/hw-app-btc/src/splitTransaction.ts
> +  const zcashv5 = version.equals(Buffer.from([0x05, 0x00, 0x00, 0x80]));
Maybe name it `isZcashV5` to be consistent with other variables.

2022-07-01 08:58 UTC, haammar-ledger commented on libs/ledgerjs/packages/hw-app-btc/src/splitTransaction.ts
> +  if ((overwinter || isDecred) && !zcashv5) {
Not very important but this condition looks weird, overwinter and zcash should probably be in the same condition.
Maybe: `if ((overwinter && !zcashv5) || isDecred)`
But really not important :smile:

2022-08-04 10:15 UTC, hzheng-ledger commented
Replace with https://github.com/LedgerHQ/ledger-live/pull/836

2022-08-04 10:15 UTC, closed without merging