feat(options): Display biometrics option without setting password beforehand
LedgerHQ/ledger-live pull request #5043
Opened 2023-10-12 13:05 UTC by ak-ledger

### 📝 Description

Add the option greyed out if no password setted. Modified privacy settings logics. Add analytics to password and biometrics options.
### ❓ Context

- **Impacted projects**: `LLM`
- **Linked resource(s)**: [LIVE-2398] 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 📸 Demo

![Simulator Screenshot - iPhone 14 - 2023-10-11 at 17 43 09](https://github.com/LedgerHQ/ledger-live/assets/146743014/b7f7d509-5573-4f72-ab76-ce96cda219ad)

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

[LIVE-2398]: https://ledgerhq.atlassian.net/browse/LIVE-2398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-10-13 07:26 UTC, mcayuelas-ledger commented
<img width="838" alt="Screenshot 2023-10-13 at 09 25 59" src="https://github.com/LedgerHQ/ledger-live/assets/112866305/cef0bccd-48a0-4d7b-8a40-ee1c64504cd8">
Followint this screenshot, you need to setup a password and then activate FaceID right?

2023-10-13 07:33 UTC, mcayuelas-ledger approved these changes
LGTM ! 
Could be goo ti have a screenrecord when faceId is enabled !

2023-10-13 07:33 UTC, mcayuelas-ledger commented on apps/ledger-live-mobile/src/screens/Settings/General/BiometricsRow.tsx
> +      console.error(validationPending);
clear console 🔥

2023-10-13 07:33 UTC, mcayuelas-ledger commented on apps/ledger-live-mobile/src/components/SettingsRow.tsx
> +const StyledTouchableRowContainer = styled(Flex)<{
You can have called it juste like that as it's not touchable 
```suggestion
const StyledRowContainer = styled(Flex)<{
```

Just a minor comment can be ignored !

2023-10-18 08:04 UTC, sshmaxime requested changes

2023-10-18 08:04 UTC, sshmaxime commented on apps/ledger-live-mobile/src/screens/Settings/General/AuthSecurityToggle.tsx
> +/** COMPONENT */
I think we should avoid doing this

2023-10-19 14:36 UTC, valpinkman commented on apps/ledger-live-mobile/src/screens/Settings/General/AuthSecurityToggle.tsx
> +/** COMPONENT */
agreed with  @sshmaxime here

2023-10-25 08:04 UTC, sshmaxime requested changes

2023-10-25 08:04 UTC, sshmaxime commented on apps/ledger-live-mobile/src/screens/Settings/General/AuthSecurityToggle.tsx
> +      toggle: "Password Lock", // Moyen de chopper la key non traduite ?
No, AFAIK stuff like that are in English. You can also remove the `// Add onClick Analytics` it's already pretty straightforward IMO.

2023-10-25 09:46 UTC, sshmaxime approved these changes

2023-10-26 08:25 UTC, merged