update @polkdadot/* dependencies
LedgerHQ/ledger-live pull request #5112
Opened 2023-10-18 08:44 UTC by lvndry

### 📝 Description

Update `@polkadot/*` dependencies

### ❓ Context

- **Impacted projects**: `LLC` `LLD` `LLM`
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8984

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2023-10-19 14:08 UTC, haammar-ledger commented
(replacing https://github.com/LedgerHQ/ledger-live/pull/4739 to attempt to pass CI)

2023-10-19 15:19 UTC, gre commented
tip for next time if you reach timeout issue on CI = they usually mean the app never loads / fails to load.

you can download the results from the CI

![Screenshot 2023-10-19 at 17 17 08](https://github.com/LedgerHQ/ledger-live/assets/211411/1710d61a-e7e1-4f1b-8fc6-4bdd9cdb1b6d)


you extract one and you can check both the html report and the videos

![Screenshot 2023-10-19 at 17 17 24](https://github.com/LedgerHQ/ledger-live/assets/211411/8a991ef8-8e2f-486e-8f48-a6623b64f0f8)

![Screenshot 2023-10-19 at 17 17 51](https://github.com/LedgerHQ/ledger-live/assets/211411/ac92202a-0f88-4cf3-aa9d-320c0aeab7b0)

from the video we see the problem

![Screenshot 2023-10-19 at 17 17 57](https://github.com/LedgerHQ/ledger-live/assets/211411/70e7331a-5365-400b-b0e7-957f9abe213f)

2023-10-19 15:23 UTC, haammar-ledger commented
@lvndry I know that you tested builds before, and I still don't see a link between the error and the changes... please see if you reproduce by testing builds now, but there's something weird here.

2023-11-13 14:54 UTC, haammar-ledger approved these changes

2023-11-13 14:59 UTC, gre requested changes
mmh, our goal should be to deduplicate polkadot , not add more dup. 
i'm looking at the typo with the `in and` in that automatic message, but we need to look why we didn't solve the polkadot dup yet 🤔

2023-11-21 12:29 UTC, gre approved these changes
looks like the bundle size script is showing improvement & things finally deduplicated 🚀

2023-11-21 13:28 UTC, haammar-ledger approved these changes
@lvndry For changes with visual impact you can provide before/after screenshots, to illustrate the change and prove that it was tested :+1:

2023-11-21 13:28 UTC, haammar-ledger commented on apps/ledger-live-desktop/src/renderer/families/polkadot/Nomination/Row.tsx
> +  console.log({ validator });
`console.log` to remove :eyes:

2023-11-21 14:21 UTC, haammar-ledger approved these changes

2023-11-23 09:41 UTC, merged