Added UTK
LedgerHQ/ledger-live pull request #535
Opened 2022-06-30 13:29 UTC by aantoniorodrigues

### 📝 Description

Added the Utrust (UTK) token to the esdt.js file since it has been migrated to the Elrond Network

### ❓ Context

- **Impacted projects**: `ledger-live` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2022-07-07 10:29 UTC, haammar-ledger requested changes
@aantoniorodrigues can you please run the following commands to update a couple test snapshots, and include them to this PR:
  - `pnpm common jest --runTestsByPath src/currencies/sortByMarketcap.test.ts -u`
  - `pnpm desktop test:jest --runTestsByPath src/generate-cryptoassets-md.test.js -u`

Thanks again.

2022-07-11 11:01 UTC, aantoniorodrigues commented
@haammar-ledger already updated the necessary test snapshots. Thank you

2022-08-03 15:46 UTC, aantoniorodrigues commented
@aelmilligy-ledger already checked the conflicting files

2022-08-12 10:00 UTC, aantoniorodrigues commented
@haammar-ledger

2022-08-23 15:42 UTC, aelmilligy-ledger commented
Hey @aantoniorodrigues, 
Thank you for your contribution.
Regarding the conflicts: 

- With the file **apps/ledger-live-desktop/cryptoassets.md**, could you merge the develop branch in your branch? 
- With the file **pnpm-lock.yaml**, could you execute the command `pnpm i`?

Thank you very much.

2022-09-07 08:15 UTC, zdenal commented on apps/ledger-live-desktop/cryptoassets.md
> +| Elrond | UTK | erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u | Utrust |  | elrond/esdt/55544B2D326638306539 |
Please update also part about number of tokens
`Tokens (10401)` -> `Tokens (10402)`
The test is failing because of it.

2022-09-07 08:19 UTC, zdenal commented on pnpm-lock.yaml
> +    path: patches/react-native-video@5.2.0.patch
I think these changes in lock should be reverted ....

2022-09-08 08:10 UTC, gre requested changes
check your PR diff, a bunch of files were changed/added and shouldn't, if it's too complex, feel free to recreate a PR with only the necessary changes 👍

2022-09-08 12:43 UTC, zdenal commented
@gre we recreated PR, can you please check? https://github.com/LedgerHQ/ledger-live/pull/1218 🙏

2022-10-01 04:57 UTC, closed without merging