feature: improve marketcap sorting using v3 cvs api
LedgerHQ/ledger-live pull request #5446
Opened 2023-11-14 15:37 UTC by gre

### 📝 Description

This reimplement the `fetchMarketcapTickers` into `fetchIdsSortedByMarketcap`, moving from `/v2/tickers` to `/v3/currencies/supported` API which uses currency id instead of tickers. That itself should improve the marketcap ordering by using the true currency id. This shift created the opportunity to simplify the code of `sortByMarketcap`.

### ❓ Context

- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-9384 

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [x] `npx changeset` was attached.
- [x] **Covered by automatic tests.** 
- [x] **Impact of the changes:** 
  - LLD and LLM projects
  - all currencies list, typically in selects
  - the Manager app list

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2023-11-14 16:44 UTC, KVNLS requested changes
This algo is really tricky.
With current implementation it's slower than before.
<img width="925" alt="image" src="https://github.com/LedgerHQ/ledger-live/assets/31533861/1da6a015-76e5-47d8-ab51-4ab16d29ffaf">

https://github.com/LedgerHQ/ledger-live/assets/31533861/2d2f7608-1520-488f-8e89-264d5333d999


You can try to reproduce by clicking on Swap quick action

2023-11-14 17:07 UTC, gre commented
@KVNLS makes sense. in future we need some benchmark tests.

i'll take a look on thurday. it will be easy to fix. at least the code is simpler but complexity probably went O(n2) on this part
```
  for (const id of ids) {
    const currency = currencies.find(c => c.type !== "FiatCurrency" && c.id === id);
    if (currency) sorted.push(currency);
  }
  ```
  
  can probably first map by id and then do the sorted push. moving to 2 loops of O(n) that way.

notice the fact we use `useCurrenciesByMarketcap` a bit everywhere nowadays (at the time we made this it was only done in top level if i recall) which means we do this multiple times (fetching from api AND sorting) maybe not the best idea overall but i'm not reconsidering this yet.

2023-11-15 16:14 UTC, haammar-ledger commented on libs/ledger-live-common/src/currencies/sortByMarketcap.react.ts
In some places we already use `.../hooks/...` for stuff that's specific to React, we should probably use only one pattern between this and `*.react.ts`

2023-11-16 10:24 UTC, gre commented
I have reworked my code, indeed there were a performance regression (2.5x slower), my new implementation will be 35x faster 🚀 

proof https://gist.github.com/gre/fe66ec88fa3de0767952591763bd0a67

```
> node index.js

currencies: 7915
v0_sortByMarketcap x 13.42 ops/sec ±0.58% (36 runs sampled)
v1_sortCurrenciesByIds x 5.61 ops/sec ±7.98% (19 runs sampled)
v2_sortCurrenciesByIds x 472 ops/sec ±3.76% (81 runs sampled)
```

2023-11-16 10:28 UTC, gre commented on libs/ledger-live-common/src/currencies/sortByMarketcap.react.ts
for now i'm just splitting the file in two and keep things collocated, we can reconsider the file tree but it have bigger consequence than the scope here, i think we're just heading toward the idea that:

- step 1: split the react usage out into dedicated files
- step 2: reunify all into another library (or hooks/ files) , but best is actually to get rid of it all completely to make live-comon no longer react dependent

![Screenshot 2023-11-16 at 11 26 19](https://github.com/LedgerHQ/ledger-live/assets/211411/7b8ded90-0f89-4844-ae49-b95030f3af77)

2023-11-16 11:36 UTC, gre commented on libs/ledgerjs/packages/types-cryptoassets/src/index.ts
> +   * @deprecated this field will soon be dropped. this is the API that drives this dynamically.
no issue.

2023-11-16 11:59 UTC, KVNLS approved these changes
Great improvements, congrats! This will improve a lot of user flows, this is even faster than before, thanks a lot!
(I only focused my review on sortByMarketCap and Swap flow)

2023-11-16 12:00 UTC, gre commented on libs/ledgerjs/packages/types-cryptoassets/src/index.ts
> +   * @deprecated this field will soon be dropped. this is the API that drives this dynamically.
maybe there is :D i can gen client side tho, weird

2023-11-21 12:32 UTC, merged