fix(LLM/postOnboarding): Fixed post onboarding not properly closed causing it to reopen
LedgerHQ/ledger-live pull request #5594
Opened 2023-11-27 16:39 UTC by mle-gall

### 📝 Description

Fixed post onboarding not properly closed causing it to reopen

### ❓ Context

- **JIRA or GitHub link**: 

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - 

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2023-11-27 16:42 UTC, KVNLS requested changes

2023-11-27 16:42 UTC, KVNLS commented on apps/ledger-live-mobile/src/logic/postOnboarding/useCompletePostOnboarding.ts
> +  const allowClosingScreen = useRef<boolean>(true);
🗑️?

2023-11-27 16:42 UTC, KVNLS commented on apps/ledger-live-mobile/src/logic/postOnboarding/useCompletePostOnboarding.ts
> +    allowClosingScreen.current = true;
🗑️?

2023-11-28 08:34 UTC, mcayuelas-ledger approved these changes

2023-11-28 14:55 UTC, merged