[LIVE-10137] [CI] - [Github Actions] - Improve clarity of run actions
LedgerHQ/ledger-live pull request #5642
Opened 2023-12-04 11:13 UTC by jdabbech-ledger

### 📝 Description
Improve clarity of git run actions in workflows

### ❓ Context

- **JIRA or GitHub link**: LIVE-10137 

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - 

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2023-12-12 10:20 UTC, aussedatlo commented on apps/ledger-live-mobile/scripts/e2e-ci.sh
> +#!/usr/bin/env bash
You need to add `set -e` at the beginning of the file.

Right now, if one of the command inside the build/test function encounters an error, the script will continue and will return 0. So it's impossible to catch an error from the CI side.

With `set -e` if a command encounters an error, the script will halt and will return the matching error code.

2023-12-12 10:20 UTC, aussedatlo commented on apps/ledger-live-mobile/scripts/e2e-ci.sh
> +  exit 0
no need to `exit 0` here

2023-12-12 10:20 UTC, aussedatlo commented on apps/ledger-live-mobile/scripts/e2e-ci.sh
> +fi
no new line after the `fi` ?

2023-12-15 16:15 UTC, valpinkman requested changes
Except for the token that needs to be an argument now, everything seems fine to me ;)

2023-12-15 16:15 UTC, valpinkman commented on apps/ledger-live-desktop/scripts/ci-lint.mjs
> +      --token="yolo" \\
sorry I have added this as a parameter, we need to pass the server token (yolo) as argument

2023-12-15 16:15 UTC, valpinkman commented on apps/ledger-live-desktop/scripts/ci-lint.mjs
> +      --token="yolo" \\
same here, we need to pass the token as arg

2023-12-20 10:03 UTC, valpinkman requested changes

2023-12-27 10:25 UTC, valpinkman approved these changes

2023-12-27 12:44 UTC, merged