fix(protect-2846): allow restore on lns+
LedgerHQ/ledger-live pull request #5674
Opened 2023-12-06 11:11 UTC by stephane-lieumont-ledger

### 📝 Description

- Allow restore flow recover with LNS+ previous version

### ❓ Context

- [JIRA PROTECT-2846](https://ledgerhq.atlassian.net/browse/PROTECT-2846)

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - 

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2023-12-06 11:25 UTC, Justkant requested changes
Small detail on the error handling

2023-12-06 11:27 UTC, stephane-lieumont-ledger commented on apps/ledger-live-desktop/src/renderer/components/RecoverRestore/index.tsx
>          setError(error);
https://github.com/LedgerHQ/ledger-live/pull/5674/commits/85e3a01830650e2c18a5773a57a646c0934f2518

2023-12-06 13:15 UTC, Justkant approved these changes
LGTM

2023-12-06 17:23 UTC, stephane-lieumont-ledger reviewed
We need to investigate, how can we manage too hold device with firmware version that not recognize Recover

2023-12-07 10:05 UTC, alexalouit requested changes

2023-12-07 10:05 UTC, alexalouit commented on apps/ledger-live-desktop/src/renderer/components/RecoverRestore/index.tsx
> +            seedPhraseType: SeedPhraseType.TwentyFour,
I'm not sure to understand, why do we set a 24 words type if the device is not onbarded?

2023-12-07 10:31 UTC, Justkant requested changes

2023-12-07 10:31 UTC, Justkant commented on apps/ledger-live-desktop/src/renderer/components/RecoverRestore/index.tsx
> +          error instanceof DeviceNotOnboarded
I would prefer if we did an util with the code from this so we also support stax error https://github.com/LedgerHQ/ledger-live/blob/8fe0797008950ba25d966442f2767a932ebf87c1/apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx#L437-L440

2023-12-07 12:13 UTC, Justkant approved these changes

2023-12-07 12:40 UTC, alexalouit approved these changes

2023-12-07 19:01 UTC, merged