feat(LLM/send): New gas fees parent account error
LedgerHQ/ledger-live pull request #5780
Opened 2023-12-19 10:18 UTC by mle-gall

### 📝 Description

New insufficient funds errors when selecting a token for which the parent account doesn't have enough balance to pay gas fees + partial visual rework of the gas fees selector (colors & border radii)

https://github.com/LedgerHQ/ledger-live/assets/39890664/b50b77a3-8f5f-473a-8b4c-d6b1437a0d83

### ❓ Context

- **JIRA or GitHub link**:  [LIVE-9792]

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - 

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2023-12-19 14:43 UTC, cgrellard-ledger commented on apps/ledger-live-mobile/src/components/SelectFeesStrategy.tsx
> +  const insufficuentError = errors?.[Object.keys(errors)[0]] || null;
Isn't it the same as `Object.values(errors)[0]` ?

2023-12-19 14:43 UTC, cgrellard-ledger commented on apps/ledger-live-mobile/src/families/evm/SelectFeesStrategy.tsx
> +  const insufficuentError = errors?.[Object.keys(errors)[0]] || null;
Same

2023-12-19 14:57 UTC, mle-gall commented on apps/ledger-live-mobile/src/components/SelectFeesStrategy.tsx
> +              title={(<TranslatedError error={insufficuentError} />) as unknown as string}
No idea why. I had a TS error there but not on the other file...
TS is sometimes driving me crazy.

2023-12-20 11:01 UTC, KVNLS commented on apps/ledger-live-mobile/src/components/SelectFeesStrategy.tsx
> +              title={(<TranslatedError error={insufficuentError} />) as unknown as string}
It comes from the type defined for `title: string;`. If we want to accept a React component as title props we need to update the type in Alert component.

2023-12-20 11:17 UTC, KVNLS requested changes
How do we know that only Bitcoin and evm are impacted?

2023-12-20 11:17 UTC, KVNLS commented on apps/ledger-live-mobile/src/components/SendRowsFee.tsx
>    if (perFamily.hasOwnProperty(mainAccount.currency.family)) {
I know it was already like this but could you fix this eslint error, please?
```suggestion
  const hasFamilyProperty = Object.prototype.hasOwnProperty.call(
    perFamily,
    mainAccount.currency.family,
  );

  if (hasFamilyProperty) {
```

2023-12-20 11:17 UTC, KVNLS commented on libs/coin-evm/src/getTransactionStatus.ts
> +      // "You need {{fees}} {{ticker}} for network fees to swap as you are on {{cryptoName}} network. <link0>Buy {{ticker}}</link0>"
🗑️

2024-01-12 10:02 UTC, KVNLS approved these changes

2024-01-12 16:01 UTC, merged