Feat/migrate v3 onboarding
LedgerHQ/ledger-live pull request #593
Opened 2022-07-06 16:26 UTC by pierrelouis-c

### 📝 Description

Migrate v3 onboarding to the main repository

### ❓ Context

- **Impacted projects**: `ledger-live-desktop` 
- **Linked resource(s)**: `[FAT-104]` 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

[FAT-104]: https://ledgerhq.atlassian.net/browse/FAT-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-07-12 13:14 UTC, grsoares21 commented on apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Welcome/Carousel.tsx
> +  const onMouseEnter = () => setPaused(true);
can use useCallback here too

2022-07-12 13:58 UTC, pierrelouis-c commented on apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/SelectUseCase/UseCaseOption.tsx
> +  color: ${p => p.theme.colors.palette.neutral.c100};
Yes but there is a lot like these. Maybe I should make another PR to factorize all styled.div to remove them and just use the components props?

2022-07-12 14:05 UTC, pierrelouis-c commented on apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Welcome/index.tsx
> +          {colors.palette.type === "dark" ? (
Yes that is right

2022-07-12 14:14 UTC, ofreyssinet-ledger requested changes

2022-07-13 12:10 UTC, ofreyssinet-ledger commented
/generate-screenshots

2022-07-13 16:01 UTC, ofreyssinet-ledger commented
/generate-screenshots

2022-07-15 08:07 UTC, ofreyssinet-ledger commented
/generate-screenshots

2022-07-15 14:18 UTC, ofreyssinet-ledger commented
/generate-screenshots

2022-07-19 16:05 UTC, pierrelouis-c commented
/generate-screenshots

2022-07-26 15:48 UTC, gre commented
@pierrelouis-c seems like the e2e tests are still failing?

2022-08-16 15:47 UTC, gre commented
@pierrelouis-c Hi, it seems like there are some errors, could you check? (and merge develop)

2022-08-17 09:27 UTC, pierrelouis-c commented
@gre I rebased develop. E2E tests will fail, because we have to re generate screenshots. We will do it right before merging into develop.

2022-08-30 14:45 UTC, pierrelouis-c commented on apps/ledger-live-desktop/src/renderer/Default.jsx
> +              {hasCompletedOnboarding && (
We hide the other routes because in the case of USB debugging we don't want to show the other components

2022-09-01 09:25 UTC, pierrelouis-c commented
/generate-screenshots

2022-09-01 12:16 UTC, pierrelouis-c commented
/generate-screenshots

2022-09-01 13:02 UTC, grsoares21 approved these changes

2022-09-01 13:26 UTC, pierrelouis-c commented
/generate-screenshots

2022-09-01 15:50 UTC, pierrelouis-c commented
/generate-screenshots

2022-09-01 21:01 UTC, pierrelouis-c commented
/generate-screenshots

2022-09-02 12:43 UTC, pierrelouis-c commented
/generate-screenshots

2022-09-02 13:17 UTC, pierrelouis-c commented
/generate-screenshots

2022-09-02 15:37 UTC, pierrelouis-c commented
/generate-screenshots

2022-09-02 15:57 UTC, pierrelouis-c commented
/generate-screenshots

2022-09-05 12:57 UTC, merged