Remove windows and mac when we run ui tests in CI
LedgerHQ/ledger-live pull request #6191
Opened 2024-02-14 09:13 UTC by KVNLS

### 📝 Description

As done for e2e tests, we don't have any benefit to replay UI tests on windows + MacOS, we can only keep linux

### ❓ Context

- **JIRA or GitHub link**: 

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-02-14 15:40 UTC, mcayuelas-ledger approved these changes

2024-02-15 12:24 UTC, gre approved these changes

2024-02-15 12:25 UTC, gre requested changes
the report is broken

https://github.com/LedgerHQ/ledger-live/pull/6191/checks?check_run_id=21571575076

![Capture d’écran 2024-02-15 à 13 25 29](https://github.com/LedgerHQ/ledger-live/assets/211411/b1f59d70-f5f2-4df4-8360-205e8e214182)

2024-02-16 09:59 UTC, KVNLS commented
@gre Thanks for spotting the Report. I fixed it:
<img width="563" alt="image" src="https://github.com/LedgerHQ/ledger-live/assets/31533861/67ba3373-ba78-430e-b314-65759d68de21">

2024-02-16 14:52 UTC, gre approved these changes

2024-02-16 14:52 UTC, merged