LIVE-2643 LIVE-2914 fix xpub null and "hash" to "id" migration
LedgerHQ/ledger-live pull request #627
Opened 2022-07-11 23:09 UTC by hzheng-ledger

### 📝 Description

1. When we did the migration from the field "hash" to "id", the bitcoin sync may be broken
2. xpub is undefined during sync from sentry report. we try to fix it in this PR

### ❓ Context

- **Impacted projects**: `` LLC
- **Linked resource(s)**: 
https://ledgerhq.atlassian.net/browse/LIVE-2643
https://ledgerhq.atlassian.net/browse/LIVE-2914

### ✅ Checklist

- [X] **Test coverage** 
- [X] **Atomic delivery** 
- [X] **No breaking changes** 

### 📸 Demo

No demo for a bug fix

### 🚀 Expectations to reach

Bitcoin sync correctly

2022-07-15 09:04 UTC, gre requested changes
- need a changelog
- how is this covered by tests? maybe there are existing tests? 

thanks

2022-07-15 11:22 UTC, haammar-ledger submitted a review, later dismissed

2022-07-15 11:28 UTC, haammar-ledger requested changes
@hzheng-ledger For test coverage of the `xpub` field, actually it would be enough to just remove it [here](https://github.com/LedgerHQ/ledger-live/blob/acdd59af6dcfcda1d136ccbfc8fdf49311485a32/libs/ledger-live-common/src/families/bitcoin/datasets/bitcoin.ts#L137) and [here](https://github.com/LedgerHQ/ledger-live/blob/acdd59af6dcfcda1d136ccbfc8fdf49311485a32/libs/ledger-live-common/src/families/bitcoin/datasets/bitcoin.ts#L163).

2022-07-15 21:06 UTC, hzheng-ledger commented
> Thanks a lot for the help. Fixed



> @hzheng-ledger For test coverage of the `xpub` field, actually it would be enough to just remove it [here](https://github.com/LedgerHQ/ledger-live/blob/acdd59af6dcfcda1d136ccbfc8fdf49311485a32/libs/ledger-live-common/src/families/bitcoin/datasets/bitcoin.ts#L137) and [here](https://github.com/LedgerHQ/ledger-live/blob/acdd59af6dcfcda1d136ccbfc8fdf49311485a32/libs/ledger-live-common/src/families/bitcoin/datasets/bitcoin.ts#L163).

2022-07-18 15:16 UTC, gre approved these changes

2022-07-18 16:41 UTC, haammar-ledger approved these changes

2022-07-18 16:42 UTC, merged