Feat/live 11532
LedgerHQ/ledger-live pull request #6400
Opened 2024-03-08 13:19 UTC by LucasWerey

### 📝 Description
Implementation of the logic and the ui of variant A for the FF privacy analytics. Add alias for the newArch named LLD/

Portfolio : 

https://github.com/LedgerHQ/ledger-live/assets/73439207/3e6225a8-3483-44cd-ae7d-b5b3f4d5c9b2

Welcome : 

https://github.com/LedgerHQ/ledger-live/assets/73439207/525f48f1-7345-49f2-822f-b616e16ac911

### ❓ Context

- **JIRA or GitHub link**: 

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-03-08 13:43 UTC, LucasWerey commented on apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Welcome/index.tsx
> -          {isFeatureFlagsSettingsButtonDisplayed && (
Will be changed (test purpose only)

2024-03-08 14:04 UTC, mcayuelas-ledger requested changes
Nice work btw 😉

2024-03-08 14:04 UTC, mcayuelas-ledger commented on apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/components/RevokeInfoField/index.tsx
> +  const privacyPolicyUrl = urls.privacyPolicy;
You can use `useLocalizedUrl`, it will allows to have urls localized and based on LLD locale settings

2024-03-08 14:04 UTC, mcayuelas-ledger commented on apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/index.tsx
> +    const isNotOnBoarding = entryPoint?.toLocaleLowerCase() !== EntryPoint.onboarding;
you can remove `toLocaleLowerCase `

2024-03-08 14:04 UTC, mcayuelas-ledger commented on apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Welcome/index.tsx
> +    entryPoint: "onboarding",
```suggestion
    entryPoint: EntryPoint.onboarding
```

2024-03-11 10:08 UTC, mcayuelas-ledger commented on apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantA/Main/components/MainBody/components/index.tsx
Already exported as default in file above?

2024-03-11 10:09 UTC, mcayuelas-ledger approved these changes
LGTM

2024-03-11 10:15 UTC, merged