feat(lld): Impletation of variant B for analytics FF
LedgerHQ/ledger-live pull request #6424
Opened 2024-03-12 12:54 UTC by LucasWerey

### 📝 Description

Implementation of the variant B of the analytics feature flag 
To see it you have to reset your LLD (so  hasSeenAnalyticsOptInPrompt will be false) and activate the feature flag lldAnalyticsOptInPrompt in the settings with the following override : 
`{"enabled":true,"params":{"variant":"B","entryPoints":["Onboarding","Portfolio"]}}`

Demo welcome page : 

https://github.com/LedgerHQ/ledger-live/assets/73439207/f9c1fe5c-83bc-462d-911d-00be897f9bb2

Demo portfolio : 

https://github.com/LedgerHQ/ledger-live/assets/73439207/e768e43c-4fbd-4c55-be73-97ddb1a5450f

### ❓ Context

- **JIRA or GitHub link**:[LIVE-11680](https://ledgerhq.atlassian.net/browse/LIVE-11680) and [LIVE-11533](https://ledgerhq.atlassian.net/browse/LIVE-11533) 

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-03-15 09:39 UTC, mcayuelas-ledger requested changes

2024-03-15 09:39 UTC, mcayuelas-ledger commented on apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/hooks/useVariantB.tsx
> +  };
```suggestion
  const setupAnalytics = (value: boolean) => {
    dispatch(setShareAnalytics(value));
    goToPersonalizedRecommandations();
    trackAnalyticsClick(value);
  };
  
  const acceptAnalytics = () => setupAnalytics(true)
  const rejectAnalytics = () => setupAnalytics(false)
 
```

2024-03-15 09:39 UTC, mcayuelas-ledger commented on apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/hooks/useVariantB.tsx
> +  };
Same as above :)

2024-03-15 09:39 UTC, mcayuelas-ledger commented on apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantB/index.tsx
> +        })()}
As you have only 2 steps : 

```suggestion
        {currentStep === 0 ? 
        <AnalyticsScreen currentTheme={currentTheme} />  : <RecommandationsScreen currentTheme={currentTheme} />
          }

```

2024-03-18 16:03 UTC, cgrellard-ledger commented on apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantB/components/Footer/index.tsx
> +  const handleAcceptClick = () => {
Can we move this logic in the hook ?

2024-03-18 17:02 UTC, cgrellard-ledger approved these changes

2024-03-18 18:14 UTC, merged