feat(lld): change general settings toggles to fit with FF
LedgerHQ/ledger-live pull request #6427
Opened 2024-03-12 15:33 UTC by LucasWerey

### 📝 Description
Change general Settings Toggles. If the FF is enabled we will display the two toggles : Analytics and Personalized Experience. If not we will display the initial toggle. Add also the track methods to track the state of toggles.
Also correct the wording for the store : setSharePersonalizedRecomm`a`ndations => setSharePersonalizedRecomm`e`ndations and sharePersonalizedRecomm`a`ndationsSelector => sharePersonalizedRecomm`e`ndationsSelector

Demo :

https://github.com/LedgerHQ/ledger-live/assets/73439207/3f2bd169-8874-4e78-a479-c02552372f23

### ❓ Context

- **JIRA or GitHub link**: 

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-03-15 09:27 UTC, mcayuelas-ledger requested changes

2024-03-15 09:27 UTC, mcayuelas-ledger commented on apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/index.tsx
> +  }, [lldAnalyticsOptInPromptFlag]);
You just need that line and then do
```suggestion
  const lldAnalyticsOptInPromptFlag = useFeature("lldAnalyticsOptInPrompt");

{lldAnalyticsOptInPromptFlag?.enabled && (<YourComponent>}


```

2024-03-18 15:57 UTC, cgrellard-ledger approved these changes

2024-03-18 16:43 UTC, mcayuelas-ledger approved these changes

2024-03-18 18:08 UTC, merged