[LLD] - [LIVE-11842] - Remove the spams NFT in custom lock screen on LLD
LedgerHQ/ledger-live pull request #6637
Opened 2024-04-09 12:19 UTC by sshmaxime

### ✅ Checklist

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

This PR remove the spams NFT in custom lock screen on LLD.

**Before:**
<img width="848" alt="Screenshot 2024-04-09 at 14 15 50" src="https://github.com/LedgerHQ/ledger-live/assets/25589782/92ac294d-01cd-4b6d-af05-c42686e9b86f">

**After:**
<img width="848" alt="Screenshot 2024-04-09 at 14 15 57" src="https://github.com/LedgerHQ/ledger-live/assets/25589782/72832c6d-2b9d-40fa-9e49-346dbae679f4">

### ❓ Context

- **JIRA or GitHub link**: [LIVE-11842] 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-04-09 13:42 UTC, mcayuelas-ledger approved these changes

2024-04-09 14:17 UTC, ofreyssinet-ledger submitted a review, later dismissed
lgtm 👍

2024-04-10 09:19 UTC, mcayuelas-ledger requested changes

2024-04-10 09:19 UTC, mcayuelas-ledger commented on apps/ledger-live-desktop/src/renderer/components/CustomImage/NFTGallerySelector.tsx
> +      nfts.slice(0, displayedCount).map((nft, index) => {
We have to think if for whatever reason we turn off FF

nftsFromSimplehashFeature?.enabled ? nfts : nftsOrdered

2024-04-10 09:55 UTC, mcayuelas-ledger approved these changes

2024-04-10 14:02 UTC, mcayuelas-ledger approved these changes

2024-04-10 14:36 UTC, ofreyssinet-ledger approved these changes

2024-04-10 14:36 UTC, merged