[LLD] - [LIVE-12209] - Add Wallet Sync in LLD settings
LedgerHQ/ledger-live pull request #6763
Opened 2024-04-26 12:06 UTC by sshmaxime

### ✅ Checklist

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

This PR adds WalletSync in LLD settings.

### ❓ Context

- **JIRA or GitHub link**: [LIVE-12209] 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-04-26 12:24 UTC, mcayuelas-ledger requested changes

2024-04-26 12:24 UTC, mcayuelas-ledger commented on apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/index.tsx
> +
```suggestion
      <FeatureToggle featureId="lldWalletSync">
          <Row
            title={t("settings.display.walletSync")}
            desc={t("settings.display.walletSyncDesc")}
            dataTestId="setting-walletSync-dropDown"
          >
            <WalletSync />
          </Row>
        )}
<FeatureToggle />
```

2024-04-26 14:36 UTC, mcayuelas-ledger commented
changeset

2024-04-30 14:27 UTC, KVNLS approved these changes

2024-04-30 15:06 UTC, merged