extend expired time for trc20
LedgerHQ/ledger-live pull request #6852
Opened 2024-05-14 11:51 UTC by drakoFukayu

### ✅ Checklist

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

_Replace this text by a clear and concise description of what this pull request is about and why it is needed. Be sure to explain the problem you're addressing and the solution you're proposing._
_For libraries, you can add a code sample of how to use it._
_For bugfixes, you can explain the previous behavior and how it was fixed._
_In case of visual features, please attach screenshots or video recordings to demonstrate the changes._

### ❓ Context

- **JIRA or GitHub link**: 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-05-14 13:10 UTC, lambertkevin submitted a review, later dismissed
Validated based on code, but requires QA validation before merge

2024-05-23 17:33 UTC, gre requested changes

2024-05-23 17:33 UTC, gre commented on libs/env/src/env.ts
> -    def: false,
the default shouldn't be true.

2024-05-23 17:34 UTC, gre commented on libs/env/src/env.ts
> -    def: false,
* (ok, i didn't saw the latest commit. but just know that since it's an open PR where i'm pinged on, i naturally reviewed it)

2024-05-31 08:30 UTC, gre approved these changes

2024-05-31 08:37 UTC, lambertkevin submitted a review, later dismissed
Still requires manual testing for the Live side for non regression

2024-06-04 12:49 UTC, merged