Fix LIVE-12571
LedgerHQ/ledger-live pull request #6863
Opened 2024-05-15 15:16 UTC by KVNLS

### ✅ Checklist

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

Fix an issue where the password is not recognized anymore because of a reset of accounts attribute.

### ❓ Context

- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-12571

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-05-15 15:18 UTC, cksanders approved these changes

2024-05-15 15:22 UTC, cksanders requested changes
please add a changelog

2024-05-15 15:25 UTC, mcayuelas-ledger commented
This need to target `release` no?

2024-05-15 15:26 UTC, KVNLS commented
> This need to target `release` no?

@cksanders will handle the fix for the release

2024-05-16 08:17 UTC, mcayuelas-ledger approved these changes

2024-05-16 08:23 UTC, merged