✨ [FEAT] : Add banner for NFTs designed for Stax
LedgerHQ/ledger-live pull request #6917
Opened 2024-05-23 13:33 UTC by mcayuelas-ledger

### ✅ Checklist

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

Add banner for NFTs designed for Stax in : 
- CustomLock Screen drawer
- Collection
- Gallery
- Nft Detail viewer

<img width="610" alt="Screenshot 2024-05-23 at 15 28 47" src="https://github.com/LedgerHQ/ledger-live/assets/112866305/e0d868fe-ebec-4af7-8cf4-2a4872b3fb3e">
<img width="630" alt="Screenshot 2024-05-23 at 15 28 16" src="https://github.com/LedgerHQ/ledger-live/assets/112866305/e12803c2-6660-4859-8a51-e45346dec27c">
<img width="748" alt="Screenshot 2024-05-23 at 15 28 12" src="https://github.com/LedgerHQ/ledger-live/assets/112866305/13b76a01-c09b-4cc2-aae3-f51d1cb93ae7">
<img width="387" alt="Screenshot 2024-05-23 at 15 27 51" src="https://github.com/LedgerHQ/ledger-live/assets/112866305/9e3f4b7c-a4d1-4303-8f46-5fb009e03908">

### ❓ Context

- **JIRA or GitHub link**: [LIVE-12560] 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-05-23 13:54 UTC, sshmaxime approved these changes
🚀

2024-05-27 07:34 UTC, KVNLS requested changes

2024-05-27 07:34 UTC, KVNLS commented on apps/ledger-live-desktop/src/renderer/components/Nft/DesignedForStax.tsx
> +};
```suggestion
const LedgerLogo = ({ size, hideBackground }: DesignedForStaxTextProps) => {
  const { colors } = useTheme();
  return (
    <Flex px={size === "small" ? 1 : 2}>
      <IconsLegacy.LedgerLogoMedium
        size={size === "medium" ? 24 : size === "large" ? 36 : 16}
        color={hideBackground ? colors.neutral.c100 : colors.constant.white}
      />
    </Flex>
  );
};
```

If children is not used, why do we not remove it from props?

2024-05-27 07:34 UTC, KVNLS commented on apps/ledger-live-desktop/src/renderer/components/Nft/DesignedForStax.tsx
> +);
As TagText is only used here and never with children, why do we use the children?

2024-05-27 07:34 UTC, KVNLS commented on apps/ledger-live-desktop/src/renderer/components/Nft/DesignedForStax.tsx
> +        size={size === "medium" ? 24 : size === "large" ? 36 : 16}
We have different font sizes used here, can't we use the ones from our theme? Is there any Figma that defines these font size values?

2024-06-05 08:02 UTC, ofreyssinet-ledger approved these changes
good for device scope (custom lock screen component)

2024-06-29 04:25 UTC, closed without merging