fix(llm): improve typing of ReceiveFunds/02-SelectAccount and fix crash case
LedgerHQ/ledger-live pull request #7148
Opened 2024-06-20 08:44 UTC by gre

- [ ] need help to test the app and ensure the fix is the correct behavior we want ('cause to me, if we want an account name, we just pass the item idk why the previous code was so complex)

### ✅ Checklist

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

the fallback case of the logic was indeed broken and unfortunately the typing was hiding the issue, we never should case using `as` in TS 😢  )

### ❓ Context

- **JIRA or GitHub link**: 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-06-20 12:23 UTC, KVNLS requested changes

2024-06-20 12:23 UTC, KVNLS commented on apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectAccount.tsx
> +          createTokenAccount: "triggerCreateAccount" in account && account?.triggerCreateAccount,
I don't think that we need to test it twice, am I missing something?
```suggestion
          createTokenAccount: "triggerCreateAccount" in account,
```

2024-06-21 08:53 UTC, KVNLS requested changes
When I look at the Sentry error, the error happens in `live-wallet/lib/accountName.js`
Could make the function resilient, please?

```
const getDefaultAccountName = (account) => {
    if (account.type === "Account") {
        return (0, exports.getDefaultAccountNameForCurrencyIndex)(account);
    }
    return account.token.name;
};
```
Here we are not sure that we can access account.token.name.
Could you add the unit test to simulate the issue we had, please?

2024-06-21 10:18 UTC, gre commented
@KVNLS the error is not in live-wallet, it's a misusage of the `getDefaultAccountName` function. Instead of giving an Account we have a CryptoCurrency.

2024-06-24 11:42 UTC, KVNLS approved these changes

2024-06-24 12:17 UTC, merged