[fix/LIVE-13101]: ensure correct trx fees for trx and trc20 swaps and sends
LedgerHQ/ledger-live pull request #7260
Opened 2024-07-04 11:41 UTC by kallen-ledger

### ✅ Checklist

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

#### TRX Swap
https://github.com/LedgerHQ/ledger-live/assets/132384348/56c5306d-c90d-45c9-af19-b6ffd390883c

#### TRC20 Swap
https://github.com/LedgerHQ/ledger-live/assets/132384348/b70bf616-878b-4944-9f1d-58a02b7988fc

### ❓ Context

https://ledgerhq.atlassian.net/browse/LIVE-13101

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-07-04 14:07 UTC, cng-ledger commented
Looks good to me, might need to give CI a few retries tho

2024-07-04 15:26 UTC, cng-ledger approved these changes

2024-07-08 08:34 UTC, cng-ledger reviewed
👏

2024-07-08 08:34 UTC, cng-ledger approved these changes

2024-07-08 08:40 UTC, lvndry requested changes

2024-07-08 08:40 UTC, lvndry commented on libs/coin-modules/coin-tron/src/bridge/getEstimateFees.ts
> +  ta?: TokenAccount | null,
Use more understandable variable names:

```suggestion
  account: Account,
  transaction: Transaction,
  tokenAccount?: TokenAccount | null,
```

2024-07-08 08:40 UTC, lvndry commented on libs/coin-modules/coin-tron/src/bridge/getEstimateFees.ts
> +  _isContract: boolean,
```suggestion
```

variable can be removed if not used

2024-07-08 08:40 UTC, lvndry commented on libs/ledgerjs/packages/cryptoassets/src/abandonseed.ts
> +  // Randomly generated inactive tron address.
I think it was nice to know how it was generated. The link seems to still be relevant

2024-07-08 12:51 UTC, lvndry approved these changes

2024-07-08 14:02 UTC, cng-ledger approved these changes

2024-07-08 14:03 UTC, merged