feat: custom errors screen
LedgerHQ/ledger-live pull request #7301
Opened 2024-07-10 08:36 UTC by chrisduma-ledger

### ✅ Checklist

- [x] `npx changeset` was attached.
- [x] **Covered by automatic tests.** 
- [x] **Impact of the changes:** 
  - ...

### 📝 Description

Address exchangeSDK errors in the LLD (`custom.exchange.error`)

### ❓ Context
[Ticket](https://ledgerhq.atlassian.net/browse/LIVE-13292)

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-07-11 08:31 UTC, sarneijim commented
Hello!
Have you test the behaviour? Can you add some screenshots?

2024-07-16 09:20 UTC, chrisduma-ledger commented
> Hello! Have you test the behaviour? Can you add some screenshots?

Yes. I've sent pictures. Let me attach one here as well

2024-07-16 09:21 UTC, chrisduma-ledger commented
Can someone from @LedgerHQ/ptx review so we can get this in?

2024-07-18 09:39 UTC, LucasWerey requested changes
Some imports adjustments
*Same as Martin

2024-07-18 09:39 UTC, LucasWerey commented on apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
> +import WalletSyncNavigator from "LLM/features/WalletSync/Navigator";
```suggestion
import WalletSyncNavigator from "LLM/features/WalletSync/WalletSyncNavigator";
```

2024-07-18 11:28 UTC, chrisduma-ledger commented
@mcayuelas-ledger @LucasWerey the wallet sync navigator is what is in the [develop](https://github.com/LedgerHQ/ledger-live/blob/develop/apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx) branch and it seems to point to the correct file. Do you have any suggestions on what the correct import would be? This happened when I fixed the conflict with the develop branch.

2024-07-18 11:29 UTC, chrisduma-ledger commented on apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts
> +import { CustomErrorNavigatorParamList } from "./CustomErrorNavigator";
not used anymore as per the latest `develop` branch update

2024-07-18 11:30 UTC, chrisduma-ledger commented on apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
> +import WalletSyncNavigator from "LLM/features/WalletSync/Navigator";
This is what is in the `develop` branch. Any suggestions for this would be greatly appreciated.

2024-07-18 14:05 UTC, mcayuelas-ledger requested changes

2024-07-22 12:03 UTC, mcayuelas-ledger commented
LGTM for Hub side

2024-07-23 13:17 UTC, LucasWerey approved these changes

2024-07-24 10:44 UTC, sarneijim approved these changes

2024-07-24 10:49 UTC, merged