[LIVE-13353][LLD] Wrong onboarding redirection between Stax and Flex
LedgerHQ/ledger-live pull request #7327
Opened 2024-07-12 14:28 UTC by jiyuzhuang

### ✅ Checklist

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

- Fix onboarding error when device connected.

### ❓ Context

- **JIRA or GitHub link**: [LIVE-13353]

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-07-12 16:45 UTC, Justkant commented
For the test to pass you might need to rebase the branch on latest develop

2024-07-15 07:46 UTC, mbertin-ledger approved these changes

2024-07-15 14:04 UTC, Justkant approved these changes

2024-07-15 14:19 UTC, mcayuelas-ledger submitted a review, later dismissed
LGTM for Hub side

2024-07-15 16:50 UTC, Justkant submitted a review, later dismissed

2024-07-16 16:06 UTC, ypolishchuk-ledger submitted a review, later dismissed

2024-07-16 16:28 UTC, mbertin-ledger requested changes

2024-07-16 16:28 UTC, mbertin-ledger commented on apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
> +          DevicesWithTouchScreen.includes(device.modelId)
[Ask] Why not use `isSyncOnboardingSupported`, because one day sync onboarding could be accessible for device like LNSP or LNX

2024-07-17 08:33 UTC, valber-ledger approved these changes

2024-07-17 08:42 UTC, mbertin-ledger approved these changes

2024-07-17 08:48 UTC, mcayuelas-ledger approved these changes
LGTM for Hub

2024-07-17 09:59 UTC, merged