[FEAT] : Manage instance with DeviceAction
LedgerHQ/ledger-live pull request #7472
Opened 2024-07-31 08:42 UTC by mcayuelas-ledger

### ✅ Checklist

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

Manage instance with DeviceAction

### ❓ Context

- **JIRA or GitHub link**: 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-08-01 12:09 UTC, KVNLS requested changes

2024-08-01 12:09 UTC, KVNLS commented on apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Could you avoid lying to React useEffect dependencies, please?

2024-08-05 08:49 UTC, gre submitted a review, later dismissed

2024-08-05 13:16 UTC, KVNLS approved these changes
🚀

2024-08-05 14:01 UTC, merged