[QAA-272][Playwright] Implement CLI commands to Speculos tests
LedgerHQ/ledger-live pull request #7987
Opened 2024-10-02 18:41 UTC by abdurrahman-ledger

### ✅ Checklist

- [ ] `npx changeset` was attached. (no need)
- [X] **Covered by automatic tests.** 
- [X] **Impact of the changes:** 
  - Playwright tests

### 📝 Description

_Replace this text by a clear and concise description of what this pull request is about and why it is needed. Be sure to explain the problem you're addressing and the solution you're proposing._
_For libraries, you can add a code sample of how to use it._
_For bugfixes, you can explain the previous behavior and how it was fixed._
_In case of visual features, please attach screenshots or video recordings to demonstrate the changes._

### ❓ Context

- **JIRA or GitHub link**: 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-10-03 12:57 UTC, KVNLS requested changes

2024-10-03 12:57 UTC, KVNLS commented on apps/cli/src/live-common-setup.ts
> +} from "../../../libs/ledgerjs/packages/hw-transport-node-speculos-http/lib/SpeculosHttpTransport";
```suggestion
} from "@ledgerhq/hw-transport-node-speculos-http";
```

2024-10-04 07:55 UTC, bharamboure-ledger submitted a review, later dismissed

2024-10-07 14:55 UTC, mcoursier-ledger approved these changes

2024-10-10 11:40 UTC, KVNLS approved these changes

2024-10-10 12:02 UTC, VicAlbr approved these changes

2024-10-10 12:35 UTC, hedi-edelbloute approved these changes

2024-10-10 12:38 UTC, merged