LIVE-3025 - Fix redirection to stories from device selection screen
LedgerHQ/ledger-live pull request #808
Opened 2022-08-02 13:18 UTC by jules-grenier-ledger

### 📝 Description

Fix the bug causing users to go back to the stories from the device selection screen

### ❓ Context

- **Impacted projects**: `ledger-live-mobile`
- **Linked resource(s)**: [LIVE-3025](https://ledgerhq.atlassian.net/browse/LIVE-3025)

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2022-08-02 13:56 UTC, LFBarreto requested changes

2022-08-02 13:56 UTC, LFBarreto commented on apps/ledger-live-mobile/src/screens/Onboarding/steps/discoverLiveInfo.tsx
>      navigation.navigate(NavigatorName.Base, {
either navigate or reset or replace but you dont need both in this case :wink:

2022-08-04 12:20 UTC, hedi-edelbloute approved these changes

2022-08-05 14:26 UTC, Justkant approved these changes

2022-08-17 15:27 UTC, ychen-ledger approved these changes
Validated with:

- LLM 3.5.0-sha.edcd41f07f1c340b43b0e83c9f04478895b21da1-release
- Android 12 / iOS 14.7

2022-08-18 08:16 UTC, merged