feat: added LDMK transport feature flag
LedgerHQ/ledger-live pull request #8093
Opened 2024-10-14 12:41 UTC by fAnselmi-Ledger

### ✅ Checklist

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

- Added ldmkTransport feature flag defaults
- Added ldmkTransport feature flag logic placeholder in LLD transport registration
- Added ldmkTransport visual flag in front-end

### ❓ Context

- **JIRA or GitHub link**: [DSDK-505](https://ledgerhq.atlassian.net/browse/DSDK-505)

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-10-14 14:17 UTC, ofreyssinet-ledger commented on libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
> +  },
[SHOULD] no need to spread anymore

2024-10-14 14:24 UTC, ofreyssinet-ledger commented on apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx
> +              )}
[COULD] maybe add a param `warningVisible: boolean` in the feature flag so that we can hide this if we want to enable it in prod one day

2024-10-14 14:24 UTC, ofreyssinet-ledger commented on apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx
> +              )}
[COULD] maybe add a param `warningVisible: boolean` in the feature flag so that we can hide this if we want to enable it in prod one day

2024-10-14 14:30 UTC, ofreyssinet-ledger reviewed
seems good, but I downloaded the build from your PR and I'm still able to connect a device via USB when the flag is enabled, so something must be wrong in the IPC transport module 🤔

2024-10-14 15:02 UTC, ofreyssinet-ledger requested changes
[SHOULD] support local overrides of the feature flag, which is only possible if you pass `localOverrides` to `getFeature({key, localOverrides})`.
To do that you'll need access to the redux store, so move the transport registration logic to a function `registerTransports(store: Store)` that will be called in init.tsx, where the store is instanciated...
It's a bit convoluted but I don't see a cleaner way to do it right now 😬

2024-10-15 09:04 UTC, valpinkman approved these changes

2024-10-15 13:18 UTC, ofreyssinet-ledger submitted a review, later dismissed

2024-10-22 08:46 UTC, cgrellard-ledger commented on apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx
> +  const ldmkTransportFlag = useFeature("ldmkTransport") as Feature_LdmkTransport;
You shouldn't use type assertion here. If you rebuild your deps you will see the type of your feature flag.
As a general rule we should avoid using the `as` keyword as much as possible.
<img width="880" alt="Screenshot 2024-10-22 at 10 44 11" src="https://github.com/user-attachments/assets/5a7a868f-2739-4b1a-b263-b522eed28fcf">

2024-10-22 08:47 UTC, themooneer commented on apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx
> +  const ldmkTransportFlag = useFeature("ldmkTransport") as Feature_LdmkTransport;
you don't need this explicit casting here

2024-10-22 08:47 UTC, cgrellard-ledger commented on apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx
> +  background: tomato;
Can we use the colors from the theme here ?

2024-10-22 08:53 UTC, themooneer commented on libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
> +      warningVisible: true,
should it be initially enabled ?

2024-10-22 09:47 UTC, Wozacosta submitted a review, later dismissed

2024-10-22 14:30 UTC, fAnselmi-Ledger commented on libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
> +      warningVisible: true,
@themooneer initially yes!

2024-10-22 14:51 UTC, cgrellard-ledger approved these changes

2024-10-24 12:58 UTC, ofreyssinet-ledger submitted a review, later dismissed

2024-10-24 13:32 UTC, ofreyssinet-ledger approved these changes

2024-10-25 08:58 UTC, Wozacosta approved these changes

2024-10-25 09:55 UTC, cgrellard-ledger approved these changes

2024-10-25 12:31 UTC, merged