fix: move crypto org into cosmos coin module
LedgerHQ/ledger-live pull request #8374
Opened 2024-11-15 10:20 UTC by qperrot

### ✅ Checklist

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

Move `cryto_org` into cosmos coin module.
Change `stakingDocUrl`

https://github.com/user-attachments/assets/318976ae-cbff-4a2f-af55-5c53beae043c

### ❓ Context

- **JIRA or GitHub link**: [LIVE-13739](https://ledgerhq.atlassian.net/browse/LIVE-13739)
-  [LIVE-15018](https://ledgerhq.atlassian.net/browse/LIVE-15018)

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

[LIVE-13739]: https://ledgerhq.atlassian.net/browse/LIVE-13739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIVE-15018]: https://ledgerhq.atlassian.net/browse/LIVE-15018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-11-15 10:59 UTC, ypolishchuk-ledger submitted a review, later dismissed

2024-11-19 12:43 UTC, Canestin requested changes
#### Manual tests on Ledger Live

1. Add Account Modal:  
   - Letters not displaying during search  
   - "Cronos POS Chain" missing  
	
	<br>
	
	<img width="280" alt="image" src="https://github.com/user-attachments/assets/ead2e1c5-c867-43c7-9ac4-3e00cfc8e032">

2024-11-19 12:50 UTC, qperrot commented on apps/ledger-live-desktop/src/newArch/features/MemoTag/constants.ts
> -  "crypto_org_croeseid",
For `crypto_org` you need to use `Cronos POS Chain`

2024-11-19 15:26 UTC, qperrot commented on apps/ledger-live-desktop/src/newArch/features/MemoTag/constants.ts
> -  "crypto_org_croeseid",
@Canestin I added memotag back !
But I can not reproduce your error about `Cronos POS Chain` missing and `Letters not displaying during search`

2024-11-19 16:09 UTC, Canestin submitted a review, later dismissed

2024-11-20 17:14 UTC, Wozacosta approved these changes
gj 🚀

2024-12-12 08:39 UTC, Canestin submitted a review, later dismissed
GG :rocket:

2024-12-12 10:34 UTC, Canestin submitted a review, later dismissed

2024-12-12 13:41 UTC, themooneer commented on apps/ledger-live-mobile/src/components/RootNavigator/types/SendFundsNavigator.ts
if the feature flag is off , we may need to have the state of the app with those deleted files no ?

2024-12-18 09:37 UTC, themooneer commented on libs/ledger-live-common/package.json
> -    "@crypto-org-chain/chain-jslib": "1.1.2",
you need to delete it from `libs/ledger-live-common/dependencies.md` table  too

2024-12-19 13:08 UTC, themooneer approved these changes
Verification tests LLD: 
- App startup ✅
- Send Flow with cosmos ✅

Verification tests LLM:
- App startup ✅

Verified bundle size 36.7mb  ✅

LGTM

2024-12-19 14:10 UTC, Wozacosta approved these changes

2024-12-20 08:50 UTC, merged