feat: ✨ Landing Page Sticky CTA Content Card
LedgerHQ/ledger-live pull request #8400
Opened 2024-11-19 13:21 UTC by mcayuelas-ledger

### ✅ Checklist

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

Add Landing Page Sticky CTA Content Card

https://github.com/user-attachments/assets/461f9550-0505-4356-b796-8e69bac2844c

### ❓ Context

- **JIRA or GitHub link**: [LIVE-14556] 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-11-20 08:41 UTC, KVNLS requested changes

2024-11-20 08:41 UTC, KVNLS commented on apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/GenericLandingPage/index.tsx
> +  const { categoriesCards, getStickyCtaCardByLandingPage, trackContentCardEvent } =
Following the new arch conventions, we might have a useViewModel hook sibling to the screen where we can put everything related to the data. So we can move the useSelector, and useDynamicContent directly inside this hook.
Then can you create a unit test to test this screen, please?

2024-11-20 10:36 UTC, KVNLS submitted a review, later dismissed
LGTM!

2024-11-21 13:06 UTC, cgrellard-ledger approved these changes

2024-11-21 14:56 UTC, merged