feat: display incompatibility message for LNS swap, LIVE-14891, LIVE-14838, LIVE-14923
LedgerHQ/ledger-live pull request #8433
Opened 2024-11-21 14:30 UTC by andreicovaciu

### ✅ Checklist

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

Adds LNS incompatibility banner for TON, ADA and SPL Tokens.
![image (6)](https://github.com/user-attachments/assets/1957602e-1435-44f3-b59f-5387efdfb2b8)

### ❓ Context

- **JIRA or GitHub link**: LIVE-14838 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-11-26 09:05 UTC, Justkant requested changes
I think we might want to handle the `renderHardwareUpdate` before the `DeviceAction` component to avoid sending APDUs to the device while showing the message

2024-12-05 14:09 UTC, Justkant commented on apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx
> +    );
We also want to move this part as it's working in the same way and for swap too

2024-12-06 08:02 UTC, Justkant commented on apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx
> +};
It doesn't seem like we use this type

2024-12-06 08:11 UTC, Justkant commented on apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx
> +};
```suggestion
```

2024-12-06 08:20 UTC, Justkant commented on apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx
> +
```suggestion
```

2024-12-06 08:20 UTC, Justkant submitted a review, later dismissed
I've tested a lot of cases with multiple devices and it now works perfectly, thx for the updates

2024-12-06 09:43 UTC, Justkant approved these changes

2024-12-06 13:28 UTC, jiyuzhuang approved these changes

2024-12-06 15:21 UTC, merged