[QAA] adding Aptos send test
LedgerHQ/ledger-live pull request #8450
Opened 2024-11-22 14:57 UTC by VicAlbr

### ✅ Checklist

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

Add e2e test

### ❓ Context

- **JIRA or GitHub link**: 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-12-03 13:57 UTC, VicAlbr commented
@hedi-edelbloute going to close the PR

2024-12-09 08:30 UTC, semeano commented on apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts
> +    xrayTicket: "",
I think we need a ticket per test type. If you check the previous one for XRP (https://ledgerhq.atlassian.net/browse/B2CQA-2816) it's related only with the "send" test.

AFAIK we don't have those tickets yet.

2024-12-09 10:05 UTC, ypolishchuk-ledger commented on apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts
> +    xrayTicket: "",
Please ask QA of your squad to provide you with test case ticket to attach here

2024-12-10 15:49 UTC, jccguimaraes commented on apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts
> +    xrayTicket: "",
Hi @ypolishchuk-ledger we don't have an assigned QA, but we will find out thanks

2024-12-10 16:19 UTC, ypolishchuk-ledger commented on apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts
> +    xrayTicket: "",
@mcoursier-ledger can you help on this one please?

2024-12-12 10:54 UTC, mcoursier-ledger requested changes

2024-12-12 10:54 UTC, mcoursier-ledger commented on apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts
> +    xrayTicket: "",
```suggestion
    xrayTicket: "B2CQA-2920",
```

2024-12-12 17:18 UTC, ypolishchuk-ledger approved these changes

2024-12-12 17:42 UTC, merged