feat(aptos): add coin feature flag
LedgerHQ/ledger-live pull request #8498
Opened 2024-11-27 11:53 UTC by jccguimaraes

### ✅ Checklist

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

Add aptos coin feature flag in the code

### ❓ Context

- **JIRA or GitHub link**: 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-11-28 06:34 UTC, themooneer commented
changeset is missing in this PR , can you add it please ?

2024-11-28 06:36 UTC, themooneer requested changes
changeset is missing in this PR , can you add it please ?

2024-11-28 10:13 UTC, hedi-edelbloute approved these changes

2024-11-29 14:18 UTC, hedi-edelbloute approved these changes

2024-11-29 15:37 UTC, merged