feat: :sparkles: (llm)add new accounts list to wallet centric screen
LedgerHQ/ledger-live pull request #8717
Opened 2024-12-17 13:06 UTC by LucasWerey

### ✅ Checklist

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [x] **Impact of the changes:** 
  - wallet centric

### 📝 Description

_Replace this text by a clear and concise description of what this pull request is about and why it is needed. Be sure to explain the problem you're addressing and the solution you're proposing._
_For libraries, you can add a code sample of how to use it._
_For bug fixes, you can explain the previous behaviour and how it was fixed._
_In case of visual features, please attach screenshots or video recordings to demonstrate the changes._

### ❓ Context

- **JIRA or GitHub link**: [LIVE-14724](https://ledgerhq.atlassian.net/browse/LIVE-14724)

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-12-19 09:10 UTC, mcayuelas-ledger commented on apps/ledger-live-mobile/src/screens/WalletCentricAsset/AccountsSection.tsx
> +import AddAccountButton from "~/newArch/features/Accounts/components/AddAccountButton";
LLM

2024-12-19 09:10 UTC, mcayuelas-ledger commented on apps/ledger-live-mobile/src/screens/WalletCentricAsset/AccountsSection.tsx
> +    if (llmAccountListUI) {
`.enabled`?

2025-01-06 10:10 UTC, mcayuelas-ledger approved these changes

2025-01-06 10:28 UTC, KVNLS requested changes

2025-01-06 10:28 UTC, KVNLS commented on apps/ledger-live-mobile/src/newArch/features/Accounts/__integrations__/accountsListScreen.integration.test.tsx
> +    return render(
As we will have more and more features using React Query, Maybe we can create a `renderWithReactQuery` method in test utils, wdyt?

2025-01-06 10:28 UTC, KVNLS commented on apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/components/AccountItem.tsx
> +  const allAccount = useSelector(accountsSelector);
Here we don't follow the new arch as the view is using selectors and has some data logic. Can you fix it, please?

2025-01-06 10:40 UTC, LucasWerey commented on apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/components/AccountItem.tsx
> +  const allAccount = useSelector(accountsSelector);
Done ✔️

2025-01-06 10:46 UTC, LucasWerey commented on apps/ledger-live-mobile/src/newArch/features/Accounts/__integrations__/accountsListScreen.integration.test.tsx
> +    return render(
Added ✔️

2025-01-06 10:48 UTC, KVNLS submitted a review, later dismissed

2025-01-06 10:56 UTC, themooneer commented on apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/index.tsx
> +          token: currency,
you mus add currency in params 
`currency: currency.parentCurrency.id`

2025-01-06 10:57 UTC, themooneer commented on apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/index.tsx
> +        screen: undefined,
wrap currency under params please

2025-01-06 10:59 UTC, themooneer commented on apps/ledger-live-mobile/src/screens/WalletCentricAsset/AccountsSection.tsx
> +    if (llmAccountListUI?.enabled) {
you need to couple it with the llmNetworkBasedAddAccount FF too , because if only llmAccountListUI , it will create a navigation error.

2025-01-06 11:14 UTC, themooneer commented on apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/index.tsx
> +  const onAddAccount = useCallback(() => {
we don't expect any analytics tracking on this action ?

2025-01-06 11:17 UTC, LucasWerey commented on apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/index.tsx
> +  const onAddAccount = useCallback(() => {
I will add them in another PR so I can focus on it !

2025-01-06 12:14 UTC, themooneer commented on apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/index.tsx
> +  const onAddAccount = useCallback(() => {
i agree

2025-01-06 12:16 UTC, themooneer commented on apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/index.tsx
> +        screen: undefined,
Well after reviewing the business logic here , you should pass by AssetSelection Navigator instead of AddAccount. 

```
navigation.navigate(NavigatorName.AssetSelection, {
        ...(currency && currency.type === "TokenCurrency"
          ? { token: currency.id, currency: currency.parentCurrency.id }
          : { currency: currency.id }),
        context: "addAccounts",
      });
```

and get rid of the if/else block. 

Reminder: We we provide the context to AssetSelection Navigator , it will manage all the redirections for add account (and in the futur receive flow).

2025-01-06 14:09 UTC, themooneer approved these changes
Replayed all the test case ✅ LGTM 

Additional Navigation Test:

From Portfolio Page 

- See all account → redirect to Accounts page 
-  → Add new or existing account CTA is there 

  - On click → redirection to the Asset Selection → SelectCrypto 

- See all asset → Asset page 

  - Select an Asset → redirection to wallet centric page with Add new or existing account CTA

-  If the asset has more than one network → redirection to Asset Selection → SelectNetwork screen ✅

  - if the asset has one single network → redirection to DeviceSelection (contex: AddAccounts) ✅

   - if the asset is a token 
    - -> if it’s parent has more than one network → redirection to Asset Selection → SelectNetwork screen ✅
    - -> if the parent is a single network currency → redirection to DeviceSelection (contex: AddAccounts) ✅

2025-01-06 14:19 UTC, merged