Feat/live 15542 aptos send receive fix send funds simulation failed when amount to send is slightly above max spendable amount
LedgerHQ/ledger-live pull request #8766
Opened 2024-12-24 17:50 UTC by may01

### ✅ Checklist

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description
During simulation of transaction, if the tx amount is lower then account balance, but we don't have enough founds to cover fees, then we get the "Abort" error from the network. 
To avoid additional message during this errors the amount check is added for the unprocessed errors. 

### ❓ Context

- **JIRA or GitHub link**: [](https://ledgerhq.atlassian.net/browse/LIVE-15542)

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

2024-12-26 17:51 UTC, joaoccmartins requested changes

2024-12-26 17:51 UTC, joaoccmartins commented on libs/ledger-live-common/src/families/aptos/js-getFeesForTransaction.ts
> +              break;
Is it possible to move this check to an early exit before line 54 `const simulation = await aptosClient.simulateTransaction(publicKeyEd, tx);`?
It seems like it to me, and that would result in tidier code (not a fan of test inside default cases)

2024-12-30 16:00 UTC, joaoccmartins approved these changes

2024-12-31 16:17 UTC, jccguimaraes approved these changes

2024-12-31 16:18 UTC, semeano approved these changes

2024-12-31 16:25 UTC, merged