bugfix/LIVE-3250: Fix multibuy access from token account
LedgerHQ/ledger-live pull request #929
Opened 2022-08-12 15:39 UTC by IAmMorrow

### 📝 Description

Accessing the multibuy live app from a token account would send the parent account id instead of the token account's, resulting in the wrong account to be initially selected in multibuy.

### ❓ Context

- **Impacted projects**: `multibuy live app` 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes**

2022-08-17 11:27 UTC, hedi-edelbloute approved these changes

2022-08-29 18:11 UTC, gre reviewed
How to cover this by test so it doesn't reproduce again?

2022-09-20 15:49 UTC, gre commented
- please define changeset
- any way to test this?

2022-09-20 15:49 UTC, gre requested changes
^

2022-10-13 04:55 UTC, closed without merging